import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { loadBrowserScripts } from "./browser_script_loader.mjs";
import { baseUrl, ensureServer, loadPlaywright, repoRoot } from "./visual-check-helpers.mjs";

const data = loadBrowserScripts(repoRoot, ["src/unit-data.js", "src/item-data.js"]);
const sources = new Set();
function visit(value) {
  if (typeof value === "string") sources.add(value);
  else if (value) Object.values(value).forEach(visit);
}
for (const key of ["RUNTIME_SPRITES", "REALITY_RUNTIME_SPRITES", "DEFEAT_STILL_SPRITES", "REALITY_DEFEAT_STILL_SPRITES"]) visit(data.FoodAnimalsUnitData[key]);
for (const key of ["ITEM_SPRITES", "ITEM_TIER_SPRITES", "REALITY_ITEM_SPRITES", "REALITY_ITEM_TIER_SPRITES"]) visit(data.FoodAnimalsItemData[key]);
const entries = [...sources].sort().map((src) => {
  const name = src.split("?")[0];
  return [name, crypto.createHash("sha256").update(fs.readFileSync(path.join(repoRoot, name))).digest("hex")];
});
const output = path.join(repoRoot, "src/sprite-metrics-data.js");
const hashFile = path.join(repoRoot, "tools/sprite-metrics-hashes.json");
if (process.argv.includes("--check")) {
  const manifest = loadBrowserScripts(repoRoot, ["src/sprite-metrics-data.js"]).FoodAnimalsSpriteMetrics;
  const hashes = JSON.parse(fs.readFileSync(hashFile, "utf8"));
  assert.deepEqual(Object.keys(manifest), entries.map(([name]) => name), "Sprite metrics coverage changed; run npm run build:sprite-metrics");
  for (const [name, hash] of entries) assert.equal(hashes[name], hash, `Sprite changed: ${name}; run npm run build:sprite-metrics`);
  console.log(`Verified alpha bounds for ${entries.length} shipped sprites.`);
} else {
  const server = await ensureServer();
  const browser = await loadPlaywright().chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.goto(`${baseUrl}/src/runtime-assets.js`);
    await page.addScriptTag({ path: path.join(repoRoot, "src/runtime-assets.js") });
    const result = {};
    for (const [src, hash] of entries) {
      result[src] = await page.evaluate(async ({ src, hash, baseUrl }) => {
        const image = new Image();
        image.src = `${baseUrl}/${src}`;
        await image.decode();
        const bounds = window.FoodAnimalsRuntimeAssets.alphaMetrics(image, new Map());
        return { width: image.naturalWidth, height: image.naturalHeight, ...bounds };
      }, { src, hash, baseUrl });
    }
    fs.writeFileSync(output, `// Generated by tools/build_sprite_metrics.mjs; do not edit.\nwindow.FoodAnimalsSpriteMetrics = Object.freeze(${JSON.stringify(result, null, 2)});\n`);
    fs.writeFileSync(hashFile, `${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`);
    console.log(`Generated alpha bounds for ${entries.length} shipped sprites.`);
  } finally { await browser.close(); server?.kill(); }
}
