(() => {
  "use strict";

  // Cache tokens in this manifest are generated by `npm run update:script-versions`.
  const SCRIPT_GROUPS = Object.freeze({
    startMenu: [
      ["dynamic-asset-manifest", "h-0bdcc5b2e185"],
      ["theme-assets", "h-3866f6adf967"],
      ["audio-settings", "h-38640bea81d8"],
      ["audio-runtime", "h-6aa53508d78a"],
      ["field-guide-runtime", "h-3ccbcafe2cf9"],
      ["run-storage", "h-207527d426cf"],
      ["food-lob-runtime", "h-1ca912fa3197"],
      ["start-menu", "h-c7b995add1fb"],
    ],
    openingVn: [
      ["dynamic-asset-manifest", "h-0bdcc5b2e185"],
      ["audio-settings", "h-38640bea81d8"],
      ["audio-runtime", "h-6aa53508d78a"],
      ["opening-vn", "h-93436a59cc20"],
    ],
    game: [
      ["dynamic-asset-manifest", "h-0bdcc5b2e185"],
      ["rng-runtime", "h-4f45df82c147"],
      ["canvas-ui", "h-dcb81679ff74"],
      ["theme-assets", "h-3866f6adf967"],
      ["slot-layout", "h-76d58f44323e"],
      ["audio-settings", "h-38640bea81d8"],
      ["audio-runtime", "h-6aa53508d78a"],
      ["shop-economy", "h-664cf36bd87e"],
      ["shop-flow-runtime", "h-bfa8c3a270c9"],
      ["card-canvas", "h-deef053d756b"],
      ["canvas-text", "h-178ce5053ce8"],
      ["runtime-assets", "h-aa054fb95e3a"],
      ["run-storage", "h-207527d426cf"],
      ["interaction-runtime", "h-d5f15b666b1c"],
      ["drag-drop-runtime", "h-557caae87942"],
      ["codex-runtime", "h-194aaf7f5e9f"],
      ["route-harness", "h-b9c626a1cd36"],
      ["reward-runtime", "h-24ef61bd7bba"],
      ["combat-ledger-capture", "h-3ec824b9375f"],
      ["combat-ledger-runtime", "h-5817ce6923ed"],
      ["options-menu-runtime", "h-afc712bb750c"],
      ["particle-runtime", "h-04e9b4528a55"],
      ["result-runtime", "h-b70dbb5298ca"],
      ["battle-flow-runtime", "h-32437862ad57"],
      ["battle-ability-runtime", "h-0435bab0dcc5"],
      ["trait-arena-runtime", "h-0554144bb124"],
      ["merge-runtime", "h-961e583a2303"],
      ["status-runtime", "h-856cf12261e8"],
      ["victory-reboot-runtime", "h-a1ec28cff1c5"],
      ["catalog-runtime", "h-9da4977b7ab9"],
      ["shop-transaction-runtime", "h-a0898420c24c"],
      ["enemy-team-runtime", "h-4a6fe15de86b"],
      ["battle-item-runtime", "h-447bb8d85d7a"],
      ["battle-canvas", "h-456e0c7c41c5"],
      ["reality-fx-canvas", "h-acfa7c0423b5"],
      ["selected-panel-canvas", "h-010344ea81ed"],
      ["slot-canvas", "h-3a0e16805387"],
      ["combat-ledger-canvas", "h-396c58499a94"],
      ["codex-canvas", "h-9701f7127530"],
      ["transition-canvas", "h-d0b4c516281a"],
      ["story-canvas", "h-33d6610869c5"],
      ["presentation-data", "h-caf977380e0f"],
      ["copy-data", "h-86f26eddcd59"],
      ["story-data", "h-b70e8344d60c"],
      ["trait-arena-data", "h-2e5155bd22b2"],
      ["unit-data", "h-497c02680e0e"],
      ["item-data", "h-fc327ab729c1"],
      ["economy-enemy-data", "h-8fd3c3963fc5"],
      ["rarity-shop-data", "h-6829c90dffeb"],
      ["status-effect-data", "h-93cdb2493911"],
      ["game", "h-7ba865476ae4"],
    ],
  });

  const entryAliases = Object.freeze({
    game: "game",
    opening: "openingVn",
    openingVn: "openingVn",
    "opening-vn": "openingVn",
    start: "startMenu",
    startMenu: "startMenu",
    "start-menu": "startMenu",
  });

  function scriptSrc(name, version) {
    return `src/${name}.js?v=${encodeURIComponent(version)}`;
  }

  function loadScript(name, version) {
    return new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.async = false;
      script.src = scriptSrc(name, version);
      script.onload = resolve;
      script.onerror = () => reject(new Error(`Failed to load ${script.src}`));
      document.body.appendChild(script);
    });
  }

  async function loadEntry(entryName) {
    const entry = entryAliases[entryName] || entryName;
    const scripts = SCRIPT_GROUPS[entry];
    if (!scripts) {
      throw new Error(`Unknown Food Animals script entry: ${entryName || "(missing)"}`);
    }
    document.documentElement.dataset.scriptEntry = entry;
    for (const [name, version] of scripts) {
      await loadScript(name, version);
    }
    document.documentElement.dataset.scriptEntryReady = "true";
  }

  const currentScript = document.currentScript;
  const requestedEntry = currentScript?.dataset.entry || document.documentElement.dataset.appEntry;

  loadEntry(requestedEntry).catch((error) => {
    document.documentElement.dataset.scriptEntryError = "true";
    console.error(error);
  });
})();
