(() => {
  "use strict";

  // Cache tokens are generated by `npm run build:runtime`.
  const BUNDLE_ENTRIES = Object.freeze({
    startMenu: ["dist/start-menu.bundle.js", "h-daa0f5aa3390"],
    openingVn: ["dist/opening-vn.bundle.js", "h-2d270392f9ee"],
    game: ["dist/game.bundle.js", "h-b3da3905660c"],
  });

  const entryAliases = Object.freeze({
    game: "game",
    opening: "openingVn",
    openingVn: "openingVn",
    "opening-vn": "openingVn",
    start: "startMenu",
    startMenu: "startMenu",
    "start-menu": "startMenu",
  });

  function scriptSrc(path, version) {
    return `${path}?v=${encodeURIComponent(version)}`;
  }

  function loadScript(path, version) {
    return new Promise((resolve, reject) => {
      const script = document.createElement("script");
      let settled = false;
      const cleanup = () => window.removeEventListener("error", handleExecutionError);
      const fail = (error) => {
        if (settled) return;
        settled = true;
        cleanup();
        reject(error);
      };
      const handleExecutionError = (event) => {
        if (!event.filename || !event.filename.startsWith(script.src.split("?", 1)[0])) return;
        fail(event.error || new Error(event.message || `Failed to execute ${script.src}`));
      };
      script.async = false;
      script.src = scriptSrc(path, version);
      window.addEventListener("error", handleExecutionError);
      script.onload = () => {
        queueMicrotask(() => {
          if (settled) return;
          settled = true;
          cleanup();
          resolve();
        });
      };
      script.onerror = () => fail(new Error(`Failed to load ${script.src}`));
      document.body.appendChild(script);
    });
  }

  async function loadEntry(entryName) {
    const entry = entryAliases[entryName] || entryName;
    const bundle = BUNDLE_ENTRIES[entry];
    if (!bundle) {
      throw new Error(`Unknown Food Animals script entry: ${entryName || "(missing)"}`);
    }
    document.documentElement.dataset.scriptEntry = entry;
    document.documentElement.dataset.scriptLoadMode = "bundle";
    await loadScript(bundle[0], bundle[1]);
    document.documentElement.dataset.scriptEntryReady = "true";
  }

  function showLoadError(error) {
    let panel = document.querySelector(".app-load-error");
    if (!panel) {
      panel = document.createElement("section");
      panel.className = "app-load-error";
      panel.setAttribute("role", "alert");
      panel.style.cssText = [
        "position:fixed",
        "inset:50% auto auto 50%",
        "transform:translate(-50%,-50%)",
        "z-index:10000",
        "max-width:min(90vw,32rem)",
        "padding:1.25rem",
        "border:2px solid #7c2638",
        "border-radius:8px",
        "background:#fff8df",
        "color:#241a19",
        "font:600 16px/1.4 system-ui,sans-serif",
        "box-shadow:0 16px 48px rgba(0,0,0,.35)",
        "text-align:center",
      ].join(";");
      const message = document.createElement("p");
      message.textContent = "Harvest Friends could not finish loading.";
      const retry = document.createElement("button");
      retry.type = "button";
      retry.textContent = "Retry";
      retry.style.cssText = "margin-top:.75rem;padding:.6rem 1rem;font:inherit;cursor:pointer";
      retry.addEventListener("click", () => window.location.reload());
      panel.append(message, retry);
      document.body.appendChild(panel);
    }
    panel.dataset.error = error?.message || "load-failed";
  }

  const currentScript = document.currentScript;
  const requestedEntry = currentScript?.dataset.entry || document.documentElement.dataset.appEntry;

  loadEntry(requestedEntry).catch((error) => {
    document.documentElement.dataset.scriptEntryError = "true";
    showLoadError(error);
    console.error(error);
  });
})();
