(() => {
  "use strict";

  // Cache tokens in this manifest are generated by `npm run update:script-versions`.
  const SCRIPT_GROUPS = Object.freeze({
    startMenu: [
      ["dynamic-asset-manifest", "h-8837ceecdfb0"],
      ["theme-assets", "h-a6fa30128df3"],
      ["audio-settings", "h-16bacfebf841"],
      ["audio-runtime", "h-045ad146f5bc"],
      ["field-guide-runtime", "h-4b79e2b56897"],
      ["run-storage", "h-5d37239279d5"],
      ["food-lob-runtime", "h-a15cd33070c2"],
      ["start-menu", "h-12bcbe4b029b"],
    ],
    openingVn: [
      ["dynamic-asset-manifest", "h-8837ceecdfb0"],
      ["audio-settings", "h-16bacfebf841"],
      ["audio-runtime", "h-045ad146f5bc"],
      ["opening-vn", "h-67799f7406b8"],
    ],
    game: [
      ["dynamic-asset-manifest", "h-8837ceecdfb0"],
      ["rng-runtime", "h-a14a985d1e20"],
      ["canvas-ui", "h-348edf62657e"],
      ["theme-assets", "h-a6fa30128df3"],
      ["slot-layout", "h-54285d4af672"],
      ["audio-settings", "h-16bacfebf841"],
      ["audio-runtime", "h-045ad146f5bc"],
      ["shop-economy", "h-150915e2936c"],
      ["shop-flow-runtime", "h-ffc6261b803d"],
      ["card-canvas", "h-68e8dd170f51"],
      ["canvas-text", "h-9d4125fc1367"],
      ["runtime-assets", "h-08465fe42a5b"],
      ["run-storage", "h-5d37239279d5"],
      ["interaction-runtime", "h-952c546698ab"],
      ["drag-drop-runtime", "h-a3b5f5228f82"],
      ["codex-runtime", "h-a11ab89f6c81"],
      ["route-harness", "h-900037aed328"],
      ["reward-runtime", "h-90e2baab36bc"],
      ["combat-ledger-capture", "h-5966a2904d24"],
      ["combat-ledger-runtime", "h-8f876fab5977"],
      ["options-menu-runtime", "h-ad628d066597"],
      ["particle-runtime", "h-fabfae4213fb"],
      ["result-runtime", "h-cca8b708a6e1"],
      ["battle-flow-runtime", "h-67296199578f"],
      ["battle-ability-runtime", "h-17e683e9fe45"],
      ["trait-arena-runtime", "h-97e385dd33e0"],
      ["merge-runtime", "h-ad49e5f884e7"],
      ["status-runtime", "h-065002c14976"],
      ["victory-reboot-runtime", "h-b5c5095fd420"],
      ["catalog-runtime", "h-160648c51031"],
      ["shop-transaction-runtime", "h-2b667ef5026f"],
      ["enemy-team-runtime", "h-2b748cf17a76"],
      ["battle-item-runtime", "h-86341550256b"],
      ["battle-canvas", "h-eccbb3df20e0"],
      ["reality-fx-canvas", "h-072bde6f0bed"],
      ["selected-panel-canvas", "h-137acabdeb4b"],
      ["slot-canvas", "h-73be59db0e31"],
      ["combat-ledger-canvas", "h-75fa2ab9f31b"],
      ["codex-canvas", "h-d9fb7a89483a"],
      ["transition-canvas", "h-fbe83b8e2c90"],
      ["story-canvas", "h-d680f38fa832"],
      ["presentation-data", "h-0f01b1bd1de4"],
      ["copy-data", "h-8fdddff7791a"],
      ["story-data", "h-51da772c2360"],
      ["trait-arena-data", "h-2e5155bd22b2"],
      ["unit-data", "h-e86eb7305d6f"],
      ["item-data", "h-ea8dc7b3dcbc"],
      ["economy-enemy-data", "h-1fc098d5a701"],
      ["rarity-shop-data", "h-e12dbb56e12f"],
      ["status-effect-data", "h-dc183b7afdae"],
      ["game", "h-b6ae2e00ec44"],
    ],
  });

  const entryAliases = Object.freeze({
    game: "game",
    opening: "openingVn",
    openingVn: "openingVn",
    "opening-vn": "openingVn",
    start: "startMenu",
    startMenu: "startMenu",
    "start-menu": "startMenu",
  });

  function scriptSrc(name, version) {
    return `src/${name}.js?v=${encodeURIComponent(version)}`;
  }

  function loadScript(name, version) {
    return new Promise((resolve, reject) => {
      const script = document.createElement("script");
      script.async = false;
      script.src = scriptSrc(name, version);
      script.onload = resolve;
      script.onerror = () => reject(new Error(`Failed to load ${script.src}`));
      document.body.appendChild(script);
    });
  }

  async function loadEntry(entryName) {
    const entry = entryAliases[entryName] || entryName;
    const scripts = SCRIPT_GROUPS[entry];
    if (!scripts) {
      throw new Error(`Unknown Food Animals script entry: ${entryName || "(missing)"}`);
    }
    document.documentElement.dataset.scriptEntry = entry;
    for (const [name, version] of scripts) {
      await loadScript(name, version);
    }
    document.documentElement.dataset.scriptEntryReady = "true";
  }

  const currentScript = document.currentScript;
  const requestedEntry = currentScript?.dataset.entry || document.documentElement.dataset.appEntry;

  loadEntry(requestedEntry).catch((error) => {
    document.documentElement.dataset.scriptEntryError = "true";
    console.error(error);
  });
})();
