(() => {
  "use strict";

  const COPY_THEMES = {
    horror: {
      meta: {
        id: "horror",
        label: "Horror / war layer",
      },
      ui: {
        actions: {
          Battle: "Deploy",
          Roll: "Scan",
          Restart: "Reboot",
          Upgrade: "Rig",
          "Max Lv": "Max Rig",
          Sell: "Scrap",
          Detach: "Strip",
        },
        status: {
          Course: "Wave",
          Coins: "Scrap",
          Health: "Hull",
        },
        panels: {
          teamIntel: "War Intel",
          foodMenu: "War Manifest",
          food: "War Machines",
          toppings: "Weapons",
          drinks: "Fuel Sources",
          arena: "ZONE",
          arenaHelp: "Zone advantage",
          arenaPressure: "Zone hazard",
        },
        types: {
          food: "Machine",
          topping: "Weapon",
          drink: "Fuel",
        },
        result: {
          runOver: "System Down",
          victory: "Relay Opened",
          defeat: "Hull Breach",
          reward: "SALVAGE",
          payout: "COMBAT PAYOUT",
          chooseReward: "Choose 1 Salvage",
          claimReward: "Claim one to rearm next wave",
          claimRetry: "Claim one to rearm this wave",
          rewardTooltipTitle: "Post-battle salvage",
          rewardTooltipBody: "Pick one salvage option before the next wave starts.",
          rewardRetryTooltipBody: "Pick one salvage option before redeploying this wave.",
          ledger: "Combat ledger",
          noLedger: "No combat details captured.",
          rewardClaimed: "Salvage claimed.",
          runEnded: "Hull failed. Reboot from the top bar.",
        },
        reality: {
          revealTitle: "ILLUSION FAILURE // WAR LAYER EXPOSED",
          revealBody: "Cozy market shell compromised. Machine conflict visible beneath.",
          activeTitle: "SIMULATION MALFUNCTION",
          activeBody: "",
          forcedHorror: "Horror layer forced",
          forcedCozy: "Cozy illusion forced",
          autoBroken: "Combat layer active",
          autoCozy: "Auto theme",
          triggerMessage: "ILLUSION FAILURE - combat layer exposed",
          triggerLog: "Illusion failed: future war layer exposed",
        },
      },
      traits: {
        breakfast: { label: "Dawn", short: "DWN" },
        bakery: { label: "Foundry", short: "FND" },
        ocean: { label: "Flood", short: "FLD" },
        sweet: { label: "Serum", short: "SRM" },
        spicy: { label: "Thermal", short: "THR" },
        street_food: { label: "Convoy", short: "CNV" },
        snack: { label: "Shrapnel", short: "SHP" },
        fresh: { label: "Cleanroom", short: "CLN" },
      },
      families: {
        bakery: "Foundry Chassis",
        seafood: "Tideframe",
        savory: "Assault Frame",
        fruit: "Vita Core",
        snack: "Shrapnel Platform",
        breakfast: "Dawn Division",
        spice: "Thermal Frame",
        dairy: "Cryo Frame",
        "dim-sum": "Steamworks",
        dessert: "Serum Frame",
        fermented: "Biohazard Camo",
        drink: "Fuel System",
        salad: "Cleanroom Frame",
        salsa: "Market Warframe",
        meal: "War Machine",
      },
      roles: {
        "Table Guardian": "Bulwark Defender",
        Finisher: "Execution Rig",
        Brawler: "Assault Rig",
        Volley: "Volley Drone",
        Healer: "Repair Core",
        Skirmisher: "Raid Unit",
        "Crunch Carry": "Kettlefire Carry",
        "Syrup Support": "Shield Support",
        "Brunch Breaker": "Breach Engine",
        Control: "Suppression",
        Breaker: "Armor Breaker",
        Carry: "Main Battery",
        "Anti-Support": "Counter-Repair",
        "Builder Support": "Fabricator Support",
        "Cart Builder": "Convoy Fabricator",
        Greed: "Salvage Engine",
        Fermenter: "Biohazard Camo",
        "Lane Control": "Lane Lockdown",
        "Row Guard": "Line Guard",
        Cleanser: "Purge Unit",
        "Burn Brawler": "Thermal Bruiser",
        "Taffy Control": "Bind Control",
        Disruptor: "Signal Disruptor",
        "Copy Oracle": "Clone Oracle",
        Scaler: "Growth Engine",
        Summoner: "Drone Spawner",
        Stunner: "Shock Unit",
        "Tempo Control": "Tempo Jammer",
        "Chili Sugar": "Thermal Stim",
        "Trail Greed": "Salvage Runner",
        "Street Brawler": "Convoy Brawler",
        "Crisp Healer": "Repair Medic",
        "Cool Control": "Cryo Control",
        "Pit Thorns": "Reactive Armor",
        "Garden Opener": "Cleanroom Opener",
        "Garden Volley": "Cleanroom Volley",
        "Plate Captain": "Command Platform",
        "Sharp Dressing": "Corrosive Edge",
        "Tide Bind": "Tide Snare",
        "Mint Cleanser": "Cleanse Unit",
        "Crisp Finisher": "Clean Execution",
        "Shell Cracker": "Hull Cracker",
        "Salsa Splash": "Market Splash",
      },
      arenas: {
        sunny_breakfast_patio: {
          name: "Solar Ration Patio",
          short: "Ration",
          mood: "Dead breakfast lanes feed the culling protocol.",
          backgroundSrc: "assets/backgrounds/horror/arena-solar-ration-patio-v1.png?v=1",
          effects: [
            { tag: "HELP", text: "Dawn units start accelerated." },
            { tag: "HELP", text: "Foundry units start armored." },
            { tag: "HURT", text: "Serum support is degraded." },
          ],
        },
        rainy_fish_market: {
          name: "Flooded Protein Docks",
          short: "Docks",
          mood: "Black water and dock machines reward flood pressure.",
          backgroundSrc: "assets/backgrounds/horror/arena-flooded-protein-docks-v1.png?v=1",
          effects: [
            { tag: "HELP", text: "Flood attacks cycle faster." },
            { tag: "HELP", text: "Flood teams delay targets." },
            { tag: "HURT", text: "Foundry units spool slower." },
          ],
        },
        street_festival: {
          name: "Blackout Street Carnival",
          short: "Blackout",
          mood: "Festival grids rot into convoy signal noise.",
          backgroundSrc: "assets/backgrounds/horror/arena-blackout-street-carnival-v1.png?v=1",
          effects: [
            { tag: "HELP", text: "Convoy/Thermal/Shrapnel faster." },
            { tag: "HELP", text: "Opening hits strike harder." },
            { tag: "HURT", text: "Front rows are exposed." },
          ],
        },
        spice_bazaar: {
          name: "Ember Spice Foundry",
          short: "Foundry",
          mood: "Furnace dust makes hostile statuses linger.",
          backgroundSrc: "assets/backgrounds/horror/arena-ember-spice-foundry-v1.png?v=1",
          effects: [
            { tag: "HELP", text: "Thermal/Convoy damage rises." },
            { tag: "HELP", text: "Their statuses last longer." },
            { tag: "HURT", text: "Serum units take more damage." },
          ],
        },
        frozen_parfait_peak: {
          name: "Cryo-Dairy Vault",
          short: "Cryo",
          mood: "Frozen clone vaults reward patient scaling.",
          backgroundSrc: "assets/backgrounds/horror/arena-cryo-dairy-vault-v1.png?v=1",
          effects: [
            { tag: "HELP", text: "Serum starts armored." },
            { tag: "HELP", text: "Serum ramps after 6s." },
            { tag: "HURT", text: "Flood/Convoy attack slower." },
          ],
        },
        dim_sum_kitchen: {
          name: "Steam Canteen Block",
          short: "Canteen",
          mood: "Armored steam lets front lines hold.",
          backgroundSrc: "assets/backgrounds/horror/arena-steam-canteen-block-v1.png?v=1",
          effects: [
            { tag: "HELP", text: "Shrapnel/Dawn fronts hold." },
            { tag: "HELP", text: "Convoy support strengthens." },
            { tag: "HURT", text: "Back-row Serum softened." },
          ],
        },
      },
      units: {
        toast_tortoise: { lineName: "Bulwark Siege Tank", short: "Bulwark", forms: { 1: { name: "Toastlet Shell Tank", short: "Shell" }, 2: { name: "Butterback Guard Tank", short: "Guard" }, 3: { name: "Clubshell Bastion", short: "Bastion" }, 4: { name: "Banquet Bunker Titan", short: "Bunker" } } },
        sushi_seal: { lineName: "Tide Recon Drone", short: "Recon", forms: { 1: { name: "Tide Scout Drone", short: "Scout" }, 2: { name: "Abyss Strike Drone", short: "Striker" }, 3: { name: "Depth Gunship", short: "Gunship" }, 4: { name: "Phantom Command Subrig", short: "Phantom" } } },
        taco_tiger: { lineName: "Shellbreaker Assault Rig", short: "Breaker", forms: { 1: { name: "Taco Cadet Rig", short: "Cadet" }, 2: { name: "Loaded Fang APC", short: "Fang" }, 3: { name: "Fiesta Breach Engine", short: "Breach" }, 4: { name: "Carnival Predator Tank", short: "Predator" } } },
        berry_bat: { lineName: "Nightwing Swarm Drone", short: "Nightwing", forms: { 1: { name: "Micro Nightwing Drone", short: "Drone" }, 2: { name: "Razorwing Interceptor", short: "Wing" }, 3: { name: "Nightshade Bomber", short: "Shade" }, 4: { name: "Nightwing Command Carrier", short: "Carrier" } } },
        noodle_newt: { lineName: "Serpent Medic Rig", short: "Medic", forms: { 1: { name: "Serpent Field Crawler", short: "Tech" }, 2: { name: "Serpent Repair Rig", short: "Repair" }, 3: { name: "Combat Surgeon Engine", short: "Surgeon" }, 4: { name: "Recovery Core Siege Rig", short: "Core" } } },
        pepper_prawn: { lineName: "Thermal Lance Drone", short: "Lance" },
        hot_chip_hamster: { lineName: "Kettlefire Wheel Tank", short: "Wheel" },
        pancake_penguin: { lineName: "Dawn Shield Walker", short: "Shield", forms: { 1: { name: "Dawn Shield Scout", short: "Scout" }, 2: { name: "Aegis Support Walker", short: "Aegis" }, 3: { name: "Crown Bulwark Mech", short: "Bulwark" }, 4: { name: "Dawn Aegis Siege Walker", short: "Siege" } } },
        benedict_lobster: { lineName: "Brunchbreaker Siege Rig", short: "Breaker" },
        pretzel_python: { lineName: "Knotwire Serpent Engine", short: "Knotwire", forms: { 1: { name: "Knotwire Coil Drone", short: "Coil" }, 2: { name: "Bronze Control Engine", short: "Control" }, 3: { name: "Constrictor Siege Engine", short: "Siege" }, 4: { name: "Crowned Knotwire War Engine", short: "Crown" } } },
        curry_crab: { lineName: "Masala Claw Crawler", short: "Claw" },
        popcorn_porcupine: { lineName: "Shrapnel Quill Battery", short: "Quill", forms: { 1: { name: "Quill Battery Drone", short: "Drone" }, 2: { name: "Needleback Artillery Rig", short: "Needle" }, 3: { name: "Shrapnel Rack Platform", short: "Rack" }, 4: { name: "Shrapnel Citadel Battery", short: "Citadel" } } },
        yogurt_yeti: { lineName: "Cryo Support Golem", short: "Cryo", forms: { 1: { name: "Cryo Scout Crawler", short: "Scout" }, 2: { name: "Frostline Repair Golem", short: "Repair" }, 3: { name: "Glacier Support Engine", short: "Glacier" }, 4: { name: "Cryo Bastion Golem", short: "Bastion" } } },
        bagel_beaver: { lineName: "Foundry Dam Engine", short: "Foundry", forms: { 1: { name: "Foundry Scout Drone", short: "Scout" }, 2: { name: "Dam Builder Rig", short: "Builder" }, 3: { name: "Foundry Barricade Engine", short: "Barricade" }, 4: { name: "Fortress Foundry Engine", short: "Fortress" } } },
        bao_bun_badger: { lineName: "Steamcart Bulwark", short: "Steamcart", forms: { 1: { name: "Steamcart Scout", short: "Scout" }, 2: { name: "Steamcart Guard Rig", short: "Guard" }, 3: { name: "Convoy Bulwark Engine", short: "Convoy" }, 4: { name: "Night Siege Cart", short: "Siege" } } },
        donut_dodo: { lineName: "Phoenix Scrap Bomber", short: "Bomber", forms: { 1: { name: "Scrap Bomber Drone", short: "Drone" }, 2: { name: "Phoenix Wing Bomber", short: "Wing" }, 3: { name: "Phoenix Bomber Mech", short: "Mech" }, 4: { name: "Phoenix Scrap Titan", short: "Titan" } } },
        kimchi_chameleon: { lineName: "Thermal Camo Unit", short: "Camo", forms: { 1: { name: "Camo Scout Unit", short: "Scout" }, 2: { name: "Camo Skirmisher Drone", short: "Skirmish" }, 3: { name: "Adaptive Camo Engine", short: "Adaptive" }, 4: { name: "Thermal Dragon Camo Engine", short: "Dragon" } } },
        waffle_walrus: { lineName: "Lattice-Tusk Siege Engine", short: "Tusk", forms: { 1: { name: "Tusk Drill Drone", short: "Drone" }, 2: { name: "Tusk Assault Rig", short: "Assault" }, 3: { name: "Lattice Breaker Engine", short: "Breaker" }, 4: { name: "Lattice Behemoth Siege Engine", short: "Behemoth" } } },
        dumpling_armadillo: { lineName: "Steam-Bastion Dozer", short: "Dozer", forms: { 1: { name: "Steam Scout Dozer", short: "Scout" }, 2: { name: "Armored Steam Dozer", short: "Armor" }, 3: { name: "Pressure Shield Dozer", short: "Shield" }, 4: { name: "Steam-Bastion Siege Dozer", short: "Bastion" } } },
        lemon_meringue_lynx: { lineName: "Acid Cleanser Stalker", short: "Stalker", forms: { 1: { name: "Acid Cleanser Scout", short: "Scout" }, 2: { name: "Foam Cleanser Stalker", short: "Cleanser" }, 3: { name: "Corrosive Panther Rig", short: "Panther" }, 4: { name: "Citadel Cleanser Sphinx", short: "Sphinx" } } },
        shakshuka_shark: { lineName: "Thermal Megalodon Subtank", short: "Subtank", forms: { 1: { name: "Thermal Shark Drone", short: "Drone" }, 2: { name: "Thermal Strike Shark", short: "Striker" }, 3: { name: "Furnacefin Subtank", short: "Furnace" }, 4: { name: "Megalodon Siege Subtank", short: "Megalodon" } } },
        saltwater_taffy_otter: { lineName: "Tide Bind Strider", short: "Binder", forms: { 1: { name: "Tide Pup Drone", short: "Drone" }, 2: { name: "Bind Strider", short: "Strider" }, 3: { name: "Coil Bind Strider", short: "Coil" }, 4: { name: "Tide Control Strider", short: "Control" } } },
        croissant_kraken: { lineName: "Layered Leviathan Rig", short: "Leviathan", forms: { 1: { name: "Abyss Squid Drone", short: "Drone" }, 2: { name: "Kraken Rig", short: "Kraken" }, 3: { name: "Layered Leviathan", short: "Layered" }, 4: { name: "Abyssal Leviathan Rig", short: "Abyss" } } },
        fortune_cookie_fox: { lineName: "Oracle Chance Engine", short: "Oracle", forms: { 1: { name: "Oracle Scout Kit", short: "Scout" }, 2: { name: "Copy Chance Engine", short: "Copy" }, 3: { name: "Prophecy Vixen Rig", short: "Prophecy" }, 4: { name: "Oracle Kitsune Engine", short: "Kitsune" } } },
        mochi_mammoth: { lineName: "Festival Colossus Walker", short: "Colossus", forms: { 1: { name: "Colossus Scout Walker", short: "Scout" }, 2: { name: "Support Mammoth Rig", short: "Support" }, 3: { name: "Moonshield Mastodon", short: "Mastodon" }, 4: { name: "Festival Colossus Walker", short: "Colossus" } } },
        gingerbread_golem: { lineName: "Citadel Decoy Guardian", short: "Guardian", forms: { 1: { name: "Decoy Guardian Drone", short: "Drone" }, 2: { name: "Guardian Golem", short: "Golem" }, 3: { name: "Frostline Guardian", short: "Frostline" }, 4: { name: "Citadel Decoy Colossus", short: "Citadel" } } },
        boba_basilisk: { lineName: "Pearl Gorgon Artillery", short: "Gorgon", forms: { 1: { name: "Pearl Newt Drone", short: "Drone" }, 2: { name: "Pearl Basilisk Rig", short: "Basilisk" }, 3: { name: "Pearl Gorgon Battery", short: "Battery" }, 4: { name: "Hydra Artillery Core", short: "Hydra" } } },
        iceberg_oyster: { lineName: "Abyssal Lock Core", short: "Lock Core", forms: { 1: { name: "Pearl Lock Drone", short: "Drone" }, 2: { name: "Iceberg Lock Core", short: "Lock" }, 3: { name: "Glacier Shell Engine", short: "Glacier" }, 4: { name: "Abyssal Lock Core", short: "Abyssal" } } },
        churro_cheetah: { lineName: "Dulce Firecat Runner", short: "Runner" },
        granola_goat: { lineName: "Harvest Ram Breaker", short: "Ram" },
        breakfast_burrito_boar: { lineName: "Brunch Cart Ram", short: "Cart Ram" },
        caesar_salamander: { lineName: "Caesar Cleanser Rig", short: "Cleanser" },
        cucumber_cobra: { lineName: "Garden Coil Hydra", short: "Hydra" },
        avocado_axolotl: { lineName: "Pitguard Reactor", short: "Pitguard" },
        herb_hare: { lineName: "Greenhouse Jumper Rig", short: "Jumper" },
        green_juice_goose: { lineName: "Garden Volley Gunship", short: "Gunship" },
        caprese_capybara: { lineName: "Antipasto Harbor Platform", short: "Harbor" },
        vinaigrette_viper: { lineName: "Dressing Dragon Coil", short: "Coil" },
        kelp_koala: { lineName: "Tide-Grove Lock Drone", short: "Lockdrone" },
        melon_mint_mantis: { lineName: "Melon-Grove Reaper", short: "Reaper" },
        coconut_shrimp_sheep: { lineName: "Island Ram Artillery", short: "Artillery" },
        crab_cake_caterpillar: { lineName: "Boardwalk Moth Tank", short: "Moth Tank" },
        pico_de_gallo_gecko: { lineName: "Market-Bowl Basilisk", short: "Basilisk" },
      },
      items: {
        bean_brew: { name: "Caffeine Reactor", short: "Reactor" },
        berry_fizz: { name: "Berry Shield Cell", short: "Shield Cell" },
        garden_spritz: { name: "Cleanroom Repair Source", short: "Repair" },
        citrus_tea: { name: "Citrus Brine Battery", short: "Brine" },
        chili_crunch_cola: { name: "Thermal Overdrive Tank", short: "Overdrive" },
        pepper_broth: { name: "Pepper Armor Station", short: "Armor Fuel" },
        abyssal_shake: { name: "Abyssal Coolant Core", short: "Coolant" },
        cream_soda_float: { name: "Foam Shield Station", short: "Foam Cell" },
        tidepool_espresso: { name: "Tidepool Turbo Source", short: "Turbo" },
        avocado_lassi: { name: "Pit Repair Reservoir", short: "Reservoir" },
        chili_brine_tonic: { name: "Chili Brine Source", short: "Brine Tank" },
        market_malt: { name: "Market Malt Overcharger", short: "Overcharger" },
        maple_cloud_cocoa: { name: "Maple Cloud Reactor", short: "Cloud Core" },
        pearl_biscuit_latte: { name: "Pearl Armor Latte", short: "Pearl Core" },
        kelp_cucumber_cooler: { name: "Kelp Turbo Cooler", short: "Kelp Fuel" },
        nori_pop_slush: { name: "Nori Pop Powercell", short: "Powercell" },
        harissa_morning_shot: { name: "Harissa Brine Ampoule", short: "Ampoule" },
        pretzel_cream_soda: { name: "Pretzel Shield Reservoir", short: "Shield Res" },
        boba_night_tea: { name: "Boba Night Overdrive", short: "Night Core" },
        pico_lime_agua: { name: "Pico Lime Repair Well", short: "Repair Well" },
        night_bite_energy: { name: "Night Bite Warcell", short: "Warcell" },
        sunny_side_egg: { name: "Solar Warhead", short: "Warhead" },
        butter_pat: { name: "Grease Armor Plate", short: "Grease" },
        cheese_star: { name: "Star Shrapnel", short: "Shrapnel" },
        bacon_strips: { name: "Reactive Armor Strips", short: "Armor" },
        cherry_tomato: { name: "Red Micro-Missile", short: "Missile" },
        pickle_chip: { name: "Brine Shard", short: "Shard" },
        mushroom_cap: { name: "Spore Mine", short: "Mine" },
        pepperoni_slice: { name: "Disc Saw", short: "Saw" },
        lemon_wedge: { name: "Acid Wedge", short: "Acid" },
        olive_ring: { name: "Targeting Ring", short: "Target" },
        chili_pepper: { name: "Thermal Spike", short: "Spike" },
        avocado_fan: { name: "Pit Guard Shield", short: "Pit Shield" },
        jam_dollop: { name: "Viscous Charge", short: "Charge" },
        caramel_crown: { name: "Crown Clamp", short: "Clamp" },
        whipped_cream_puff: { name: "Foam Sealant", short: "Sealant" },
        basil_leaf: { name: "Sensor Blade Array", short: "Sensor" },
        honey_drizzle: { name: "Adhesive Gel", short: "Gel" },
        garlic_clove: { name: "Repulsor Module", short: "Repulsor" },
        rice_ball: { name: "Impact Pellet", short: "Pellet" },
        onion_ring: { name: "Razor Ring", short: "Razor" },
        maple_leaf: { name: "Amber Reservoir", short: "Reservoir" },
        marshmallow_cube: { name: "Soft Armor Cube", short: "Armor Cube" },
        cookie_crumb: { name: "Phantom Copy Chip", short: "Copy Chip" },
        seaweed_wrap: { name: "Tide Snare", short: "Snare" },
        pretzel_stick: { name: "Knotwire Spike", short: "Knotwire" },
        waffle_cone: { name: "Sabot Cone", short: "Sabot" },
        skewer: { name: "Rail Spear", short: "Rail" },
        hot_sauce_bottle: { name: "Thermal Spray", short: "Thermal" },
        sugar_cube: { name: "Stim Cube", short: "Stim" },
        mint_leaf: { name: "Decon Patch", short: "Patch" },
        soda_pop: { name: "Fizz Capacitor", short: "Capacitor" },
        salt_shaker: { name: "Crystalline Flak", short: "Flak" },
        vinegar_splash: { name: "Corrosive Sprayer", short: "Corrosive" },
        cucumber_slice: { name: "Delay Module", short: "Delay" },
        cracker_plate: { name: "Shieldbreaker Plate", short: "Breaker" },
        cherry_pit: { name: "Red Charge Mine", short: "Mine" },
        breadstick_dummy: { name: "Guard Pike", short: "Pike" },
        popcorn_kernel: { name: "Kernel Flak", short: "Flak" },
        coupon_clip: { name: "Probability Decoder", short: "Decoder" },
        lucky_grape: { name: "Luck Core", short: "Luck Core" },
        shopping_bag: { name: "Golden Supply Pod", short: "Supply" },
        recipe_card: { name: "Protocol Breaker", short: "Protocol" },
        soup_ladle: { name: "Sustain Injector", short: "Injector" },
        gravy_boat: { name: "Viscous Armor Reservoir", short: "Reservoir" },
        spice_jar: { name: "Hazard Grenade", short: "Grenade" },
        serving_tray: { name: "Signal Relay", short: "Relay" },
        glass_candy: { name: "Glass Shard", short: "Shard" },
        wasabi_pea: { name: "Wasabi Piercer", short: "Piercer" },
        molten_cheese: { name: "Molten Rounds", short: "Rounds" },
        brittle_cracker: { name: "Shellbreaker Rack", short: "Shellbreak" },
        golden_truffle_crown: { name: "Command Crown", short: "Command" },
        dragonfruit_star: { name: "Dragon Starblade", short: "Starblade" },
        rainbow_mochi: { name: "Prism Armor Node", short: "Node" },
        caviar_pearls: { name: "Cluster Mines", short: "Clusters" },
        saffron_threads: { name: "Signal Filaments", short: "Filaments" },
        scallion_oil: { name: "Vector Oil Slick", short: "Slick" },
        gochugaru_flakes: { name: "Red Flak", short: "Flak" },
        dill_sprig: { name: "Signal Mast", short: "Signal" },
        sesame_seeds: { name: "Scattershot Pods", short: "Scatter" },
        cinnamon_sugar: { name: "Burn Charge", short: "Burn" },
        milk_tea_foam: { name: "Foam Coolant", short: "Coolant" },
        royal_icing_crest: { name: "Royal Aegis Crest", short: "Aegis" },
      },
    },
  };

  window.FoodAnimalsCopyData = Object.freeze({
    COPY_THEMES,
  });
})();
