(() => {
  "use strict";

  const CATALOG = [
    {
      id: "toast_tortoise",
      name: "Toast Tortoise",
      short: "Toast",
      rarity: "common",
      family: "bakery",
      traits: ["breakfast", "bakery"],
      emoji: "TT",
      color: "#d99043",
      accent: "#85512e",
      hp: 42,
      atk: 8,
      speed: 1.18,
      role: "Table Guardian",
      ability: "taunt_guard",
      abilityText: "Taunt guard",
      forms: [
        { name: "Toastlet", short: "Toastlet" },
        { name: "Butterback", short: "Butter" },
        { name: "Clubshell", short: "Club" },
        { name: "Banquet Shell", short: "Banquet" },
      ],
    },
    {
      id: "sushi_seal",
      name: "Sushi Seal",
      short: "Sushi",
      rarity: "common",
      family: "seafood",
      traits: ["ocean", "street_food"],
      emoji: "SS",
      color: "#f2f5ef",
      accent: "#e45a6d",
      hp: 22,
      atk: 18,
      speed: 0.78,
      role: "Finisher",
      ability: "execute",
      abilityText: "Wounded snipe",
      forms: [
        { name: "Maki Pup", short: "Maki" },
        { name: "Nigiri Seal", short: "Nigiri" },
        { name: "Dragon Roll", short: "Dragon" },
        { name: "Omakase Seal", short: "Omakase" },
      ],
    },
    {
      id: "taco_tiger",
      name: "Taco Tiger",
      short: "Taco",
      rarity: "common",
      family: "savory",
      traits: ["spicy", "street_food"],
      emoji: "TG",
      color: "#f1c84b",
      accent: "#d9573c",
      hp: 34,
      atk: 14,
      speed: 0.94,
      role: "Brawler",
      ability: "cleave",
      abilityText: "Column cleave",
      forms: [
        { name: "Taco Cub", short: "Cub" },
        { name: "Loaded Tiger", short: "Loaded" },
        { name: "Fiesta Fang", short: "Fiesta" },
        { name: "Carnival Tiger", short: "Carnival" },
      ],
    },
    {
      id: "berry_bat",
      name: "Berry Bat",
      short: "Berry",
      rarity: "common",
      family: "fruit",
      traits: ["sweet", "snack"],
      emoji: "BB",
      color: "#7542a8",
      accent: "#dd5ea8",
      hp: 18,
      atk: 10,
      speed: 0.72,
      role: "Volley",
      ability: "back_row",
      abilityText: "Back row",
      forms: [
        { name: "Berry Bat", short: "Berry" },
        { name: "Bramble Bat", short: "Bramble" },
        { name: "Elderberry Bat", short: "Elder" },
        { name: "Royal Berry Bat", short: "Royal" },
      ],
    },
    {
      id: "noodle_newt",
      name: "Noodle Newt",
      short: "Noodle",
      rarity: "common",
      family: "savory",
      traits: ["spicy", "street_food"],
      emoji: "NN",
      color: "#ead77b",
      accent: "#55a375",
      hp: 24,
      atk: 8,
      speed: 0.86,
      role: "Healer",
      ability: "heal",
      abilityText: "Heals allies",
      forms: [
        { name: "Noodle Newt", short: "Noodle" },
        { name: "Ramen Newt", short: "Ramen" },
        { name: "Hotpot Newt", short: "Hotpot" },
        { name: "Cauldron Newt", short: "Cauldron" },
      ],
    },
    {
      id: "pepper_prawn",
      name: "Pepper Prawn",
      short: "Pepper",
      rarity: "common",
      family: "seafood",
      traits: ["ocean", "spicy"],
      emoji: "PR",
      color: "#f26a35",
      accent: "#5aa6d6",
      hp: 26,
      atk: 12,
      speed: 0.84,
      role: "Skirmisher",
      ability: "pepper_dash",
      abilityText: "Pepper poke",
      forms: [
        { name: "Pepper Prawn", short: "Pepper" },
        { name: "Seared Prawn", short: "Seared" },
        { name: "Chili Skewer Prawn", short: "Skewer" },
        { name: "Tidefire Prawn", short: "Tidefire" },
      ],
    },
    {
      id: "hot_chip_hamster",
      name: "Hot Chip Hamster",
      short: "Hot Chip",
      rarity: "common",
      family: "snack",
      traits: ["snack", "spicy"],
      emoji: "HC",
      color: "#e55a2a",
      accent: "#f4d35e",
      hp: 24,
      atk: 10,
      speed: 0.78,
      role: "Crunch Carry",
      ability: "kernel_combo",
      abilityText: "Crunch combo",
      forms: [
        { name: "Hot Chip Pup", short: "Chip" },
        { name: "Hot Chip Hamster", short: "Hamster" },
        { name: "Flamin' Wheel Hamster", short: "Wheel" },
        { name: "Kettlefire Hamster", short: "Kettlefire" },
      ],
    },
    {
      id: "pancake_penguin",
      name: "Pancake Penguin",
      short: "Pancake",
      rarity: "uncommon",
      family: "breakfast",
      traits: ["breakfast", "bakery"],
      emoji: "PP",
      color: "#e8b765",
      accent: "#b36a2e",
      hp: 32,
      atk: 8,
      speed: 1.04,
      role: "Syrup Support",
      ability: "syrup_start",
      abilityText: "Opening shields",
      forms: [
        { name: "Pancake Chick", short: "Chick" },
        { name: "Syrup Penguin", short: "Syrup" },
        { name: "Stack King", short: "Stack" },
        { name: "Breakfast Emperor", short: "Emperor" },
      ],
    },
    {
      id: "benedict_lobster",
      name: "Benedict Lobster",
      short: "Benny",
      rarity: "uncommon",
      family: "seafood",
      traits: ["breakfast", "ocean"],
      emoji: "BL",
      color: "#e76f51",
      accent: "#f4c95d",
      hp: 34,
      atk: 12,
      speed: 0.96,
      role: "Brunch Breaker",
      ability: "armor_break",
      abilityText: "Brunch breaker",
      forms: [
        { name: "Benny Lobster", short: "Benny" },
        { name: "Benedict Lobster", short: "Benedict" },
        { name: "Hollandaise Reef Lobster", short: "Holland" },
        { name: "Brunch Tide Monarch", short: "Monarch" },
      ],
    },
    {
      id: "pretzel_python",
      name: "Pretzel Python",
      short: "Pretzel",
      rarity: "uncommon",
      family: "snack",
      traits: ["bakery", "snack"],
      emoji: "PP",
      color: "#c47a35",
      accent: "#f0d56b",
      hp: 26,
      atk: 12,
      speed: 0.82,
      role: "Control",
      ability: "slow",
      abilityText: "Cooldown delay",
      forms: [
        { name: "Pretzel Hatchling", short: "Hatch" },
        { name: "Twist Python", short: "Twist" },
        { name: "Saltcoil", short: "Salt" },
        { name: "Knot Constrictor", short: "Knot" },
      ],
    },
    {
      id: "curry_crab",
      name: "Curry Crab",
      short: "Curry",
      rarity: "uncommon",
      family: "spice",
      traits: ["ocean", "spicy"],
      emoji: "CC",
      color: "#d9852f",
      accent: "#8d3d27",
      hp: 36,
      atk: 12,
      speed: 1,
      role: "Breaker",
      ability: "armor_break",
      abilityText: "Anti-tank",
      forms: [
        { name: "Curry Crab", short: "Curry" },
        { name: "Masala Crab", short: "Masala" },
        { name: "Spiceclaw", short: "Spice" },
        { name: "Vindaloo Titan", short: "Titan" },
      ],
    },
    {
      id: "popcorn_porcupine",
      name: "Popcorn Porcupine",
      short: "Popcorn",
      rarity: "uncommon",
      family: "snack",
      traits: ["snack", "street_food"],
      emoji: "PP",
      color: "#f4d35e",
      accent: "#9c6a2f",
      hp: 24,
      atk: 10,
      speed: 0.74,
      role: "Carry",
      ability: "kernel_combo",
      abilityText: "Combo carry",
      forms: [
        { name: "Kernel Hoglet", short: "Kernel" },
        { name: "Popcorn Porcupine", short: "Popcorn" },
        { name: "Kettle Quillbeast", short: "Kettle" },
        { name: "Cinema Needleback", short: "Cinema" },
      ],
    },
    {
      id: "yogurt_yeti",
      name: "Yogurt Yeti",
      short: "Yogurt",
      rarity: "uncommon",
      family: "dairy",
      traits: ["sweet", "snack"],
      emoji: "YY",
      color: "#f4f6ff",
      accent: "#6aa5d8",
      hp: 30,
      atk: 10,
      speed: 0.92,
      role: "Anti-Support",
      ability: "sour_aura",
      abilityText: "Cuts support",
      forms: [
        { name: "Yogurt Cub", short: "Cub" },
        { name: "Parfait Yeti", short: "Parfait" },
        { name: "Frozen Yeti", short: "Frozen" },
        { name: "Glacier Parfait", short: "Glacier" },
      ],
    },
    {
      id: "bagel_beaver",
      name: "Bagel Beaver",
      short: "Bagel",
      rarity: "uncommon",
      family: "bakery",
      traits: ["breakfast", "bakery"],
      emoji: "BV",
      color: "#c98a3a",
      accent: "#f0d56b",
      hp: 34,
      atk: 8,
      speed: 1.06,
      role: "Builder Support",
      ability: "bagel_build",
      abilityText: "Builds shields",
      forms: [
        { name: "Bagel Beaver", short: "Bagel" },
        { name: "Sesame Beaver", short: "Sesame" },
        { name: "Everything Dam Beaver", short: "Dam" },
        { name: "Brunch Lodge Beaver", short: "Lodge" },
      ],
    },
    {
      id: "bao_bun_badger",
      name: "Bao Bun Badger",
      short: "Bao",
      rarity: "uncommon",
      family: "dim-sum",
      traits: ["bakery", "street_food"],
      emoji: "BA",
      color: "#f0d8b4",
      accent: "#c05a39",
      hp: 32,
      atk: 8,
      speed: 1.04,
      role: "Cart Builder",
      ability: "bagel_build",
      abilityText: "Cart shields",
      forms: [
        { name: "Bao Bun Badger", short: "Bao" },
        { name: "Sesame Bao Badger", short: "Sesame" },
        { name: "Steam-Cart Badger", short: "Cart" },
        { name: "Night-Market Bao Boss", short: "Market" },
      ],
    },
    {
      id: "donut_dodo",
      name: "Donut Dodo",
      short: "Donut",
      rarity: "rare",
      family: "dessert",
      traits: ["breakfast", "sweet"],
      emoji: "DD",
      color: "#e7a85c",
      accent: "#d9548f",
      hp: 28,
      atk: 10,
      speed: 1.16,
      role: "Greed",
      ability: "treat_income",
      abilityText: "Survivor gold",
      forms: [
        { name: "Donut Dodo", short: "Dodo" },
        { name: "Glazed Dodo", short: "Glazed" },
        { name: "Sprinkle Roc", short: "Sprinkle" },
        { name: "Bakery Phoenix", short: "Phoenix" },
      ],
    },
    {
      id: "kimchi_chameleon",
      name: "Kimchi Chameleon",
      short: "Kimchi",
      rarity: "rare",
      family: "fermented",
      traits: ["spicy", "street_food"],
      emoji: "KC",
      color: "#e65036",
      accent: "#6a9d38",
      hp: 24,
      atk: 12,
      speed: 0.86,
      role: "Fermenter",
      ability: "status_spread",
      abilityText: "Burn/mark",
      forms: [
        { name: "Kimchi Chameleon", short: "Kimchi" },
        { name: "Ferment Gecko", short: "Ferment" },
        { name: "Gochu Chameleon", short: "Gochu" },
        { name: "Pickled Dragon", short: "Dragon" },
      ],
    },
    {
      id: "waffle_walrus",
      name: "Waffle Walrus",
      short: "Waffle",
      rarity: "rare",
      family: "breakfast",
      traits: ["breakfast", "bakery"],
      emoji: "WW",
      color: "#d8a64a",
      accent: "#6c8fbd",
      hp: 38,
      atk: 10,
      speed: 1.08,
      role: "Lane Control",
      ability: "sticky_lane",
      abilityText: "Stick lane",
      forms: [
        { name: "Waffle Pup", short: "Pup" },
        { name: "Waffle Walrus", short: "Walrus" },
        { name: "Syrup-Tusk Walrus", short: "Tusk" },
        { name: "Brunch Behemoth", short: "Brunch" },
      ],
    },
    {
      id: "dumpling_armadillo",
      name: "Dumpling Armadillo",
      short: "Dumpling",
      rarity: "rare",
      family: "dim-sum",
      traits: ["street_food", "snack"],
      emoji: "DA",
      color: "#f0dcb8",
      accent: "#8b6f50",
      hp: 44,
      atk: 8,
      speed: 1.22,
      role: "Row Guard",
      ability: "row_shield",
      abilityText: "Row shields",
      forms: [
        { name: "Dumpling Dillo", short: "Dillo" },
        { name: "Bao Armadillo", short: "Bao" },
        { name: "Dim Sum Dozer", short: "Dozer" },
        { name: "Steam-Basket Bastion", short: "Bastion" },
      ],
    },
    {
      id: "lemon_meringue_lynx",
      name: "Lemon Meringue Lynx",
      short: "Lemon",
      rarity: "rare",
      family: "dessert",
      traits: ["sweet", "bakery"],
      emoji: "LL",
      color: "#f2dc5d",
      accent: "#ffffff",
      hp: 22,
      atk: 8,
      speed: 0.8,
      role: "Cleanser",
      ability: "cleanse",
      abilityText: "Cleanse",
      forms: [
        { name: "Lemon Lynx", short: "Lemon" },
        { name: "Meringue Lynx", short: "Meringue" },
        { name: "Tart Panther", short: "Tart" },
        { name: "Citrus Sphinx", short: "Sphinx" },
      ],
    },
    {
      id: "shakshuka_shark",
      name: "Shakshuka Shark",
      short: "Shakshuka",
      rarity: "rare",
      family: "breakfast",
      traits: ["breakfast", "spicy"],
      emoji: "SH",
      color: "#e24822",
      accent: "#f4d35e",
      hp: 36,
      atk: 14,
      speed: 0.98,
      role: "Burn Brawler",
      ability: "shakshuka_burn",
      abilityText: "Breakfast burn",
      forms: [
        { name: "Shakshuka Shark", short: "Shakshuka" },
        { name: "Saucy Shark", short: "Saucy" },
        { name: "Skilletfin Shark", short: "Skillet" },
        { name: "Harissa Megalodon", short: "Harissa" },
      ],
    },
    {
      id: "saltwater_taffy_otter",
      name: "Saltwater Taffy Otter",
      short: "Taffy",
      rarity: "rare",
      family: "dessert",
      traits: ["sweet", "snack"],
      emoji: "TO",
      color: "#f2a7c7",
      accent: "#5aa6d6",
      hp: 26,
      atk: 12,
      speed: 0.84,
      role: "Taffy Control",
      ability: "slow",
      abilityText: "Taffy bind",
      forms: [
        { name: "Taffy Pup", short: "Pup" },
        { name: "Saltwater Taffy Otter", short: "Taffy" },
        { name: "Ribbon Taffy Otter", short: "Ribbon" },
        { name: "Candy-Tide Otter", short: "Candy Tide" },
      ],
    },
    {
      id: "croissant_kraken",
      name: "Croissant Kraken",
      short: "Kraken",
      rarity: "epic",
      family: "bakery",
      traits: ["bakery", "breakfast"],
      emoji: "CK",
      color: "#d69a3e",
      accent: "#6b4aa8",
      hp: 34,
      atk: 12,
      speed: 1.02,
      role: "Disruptor",
      ability: "pull_start",
      abilityText: "Pull start",
      forms: [
        { name: "Croissant Squid", short: "Squid" },
        { name: "Buttered Kraken", short: "Kraken" },
        { name: "Laminated Leviathan", short: "Leviathan" },
        { name: "Thousand-Layer Abyss", short: "Abyss" },
      ],
    },
    {
      id: "fortune_cookie_fox",
      name: "Fortune Cookie Fox",
      short: "Fortune",
      rarity: "epic",
      family: "dessert",
      traits: ["bakery", "snack", "sweet"],
      emoji: "FF",
      color: "#e4b65f",
      accent: "#d24d53",
      hp: 24,
      atk: 10,
      speed: 0.84,
      role: "Copy Oracle",
      ability: "copy_luck",
      abilityText: "Copy odds",
      forms: [
        { name: "Fortune Kit", short: "Kit" },
        { name: "Cookie Fox", short: "Cookie" },
        { name: "Prophecy Vixen", short: "Vixen" },
        { name: "Oracle Kitsune", short: "Oracle" },
      ],
    },
    {
      id: "mochi_mammoth",
      name: "Mochi Mammoth",
      short: "Mochi",
      rarity: "epic",
      family: "dessert",
      traits: ["sweet", "snack"],
      emoji: "MM",
      color: "#f2d6df",
      accent: "#8b6fb0",
      hp: 46,
      atk: 8,
      speed: 1.28,
      role: "Scaler",
      ability: "survive_scale",
      abilityText: "Survive scales",
      forms: [
        { name: "Mochi Calf", short: "Calf" },
        { name: "Mochi Mammoth", short: "Mammoth" },
        { name: "Mooncake Mastodon", short: "Mastodon" },
        { name: "Festival Colossus", short: "Colossus" },
      ],
    },
    {
      id: "gingerbread_golem",
      name: "Gingerbread Golem",
      short: "Ginger",
      rarity: "epic",
      family: "bakery",
      traits: ["bakery", "sweet"],
      emoji: "GG",
      color: "#b66b34",
      accent: "#f5f0df",
      hp: 40,
      atk: 10,
      speed: 1.14,
      role: "Summoner",
      ability: "ginger_decoy",
      abilityText: "Summons decoy",
      forms: [
        { name: "Gingerling", short: "Ginger" },
        { name: "Gingerbread Golem", short: "Golem" },
        { name: "Frosted Guardian", short: "Guardian" },
        { name: "Candy-Castle Colossus", short: "Castle" },
      ],
    },
    {
      id: "boba_basilisk",
      name: "Boba Basilisk",
      short: "Boba",
      rarity: "epic",
      family: "drink",
      traits: ["sweet", "street_food", "snack"],
      emoji: "BB",
      color: "#c99bd8",
      accent: "#3d263d",
      hp: 26,
      atk: 12,
      speed: 0.78,
      role: "Stunner",
      ability: "pearl_stun",
      abilityText: "Pearl stun",
      forms: [
        { name: "Boba Newt", short: "Newt" },
        { name: "Tapioca Basilisk", short: "Basilisk" },
        { name: "Pearl Gorgon", short: "Gorgon" },
        { name: "Bubble Tea Hydra", short: "Hydra" },
      ],
    },
    {
      id: "iceberg_oyster",
      name: "Iceberg Oyster",
      short: "Oyster",
      rarity: "epic",
      family: "seafood",
      traits: ["ocean", "snack"],
      emoji: "IO",
      color: "#d8f2ff",
      accent: "#4d9d95",
      hp: 38,
      atk: 10,
      speed: 1.06,
      role: "Tempo Control",
      ability: "iceberg_lock",
      abilityText: "Locks tempo",
      forms: [
        { name: "Iceberg Oyster", short: "Oyster" },
        { name: "Pearl-Ice Oyster", short: "Pearl" },
        { name: "Glacier Shell Oyster", short: "Glacier" },
        { name: "Abyssal Ice Pearl", short: "Abyss" },
      ],
    },
    {
      id: "churro_cheetah",
      name: "Churro Cheetah",
      short: "Churro",
      rarity: "epic",
      family: "dessert",
      traits: ["bakery", "spicy", "sweet"],
      emoji: "CH",
      color: "#c98335",
      accent: "#e24822",
      hp: 30,
      atk: 14,
      speed: 0.82,
      role: "Chili Sugar",
      ability: "status_spread",
      abilityText: "Burn/mark",
      forms: [
        { name: "Churro Cub", short: "Cub" },
        { name: "Cinnamon Cheetah", short: "Cinnamon" },
        { name: "Chili Churro Cheetah", short: "Chili" },
        { name: "Dulce Firecat", short: "Dulce" },
      ],
    },
    {
      id: "granola_goat",
      name: "Granola Goat",
      short: "Granola",
      rarity: "epic",
      family: "breakfast",
      traits: ["breakfast", "snack"],
      emoji: "GG",
      color: "#d6a04c",
      accent: "#7aa530",
      hp: 34,
      atk: 10,
      speed: 1.08,
      role: "Trail Greed",
      ability: "treat_income",
      abilityText: "Survivor gold",
      forms: [
        { name: "Oat Kid", short: "Oat" },
        { name: "Granola Goat", short: "Granola" },
        { name: "Trail-Mix Ram", short: "Trail" },
        { name: "Harvest Ibex", short: "Harvest" },
      ],
    },
    {
      id: "breakfast_burrito_boar",
      name: "Breakfast Burrito Boar",
      short: "Burrito",
      rarity: "epic",
      family: "breakfast",
      traits: ["breakfast", "street_food", "spicy"],
      emoji: "BB",
      color: "#d99736",
      accent: "#55a375",
      hp: 40,
      atk: 12,
      speed: 0.98,
      role: "Street Brawler",
      ability: "cleave",
      abilityText: "Column cleave",
      forms: [
        { name: "Egg Wrap Piglet", short: "Wrap" },
        { name: "Breakfast Burrito Boar", short: "Burrito" },
        { name: "Salsa Tusk Boar", short: "Salsa" },
        { name: "Brunch Cart Boar", short: "Cart" },
      ],
    },
    {
      id: "caesar_salamander",
      name: "Caesar Salamander",
      short: "Caesar",
      rarity: "common",
      family: "salad",
      traits: ["fresh", "snack"],
      emoji: "CS",
      color: "#78b84d",
      accent: "#f0dcb8",
      hp: 26,
      atk: 8,
      speed: 0.92,
      role: "Crisp Healer",
      ability: "heal",
      abilityText: "Crisp heal",
      forms: [
        { name: "Romaine Newt", short: "Romaine" },
        { name: "Caesar Salamander", short: "Caesar" },
        { name: "Crouton Crest", short: "Crouton" },
        { name: "Salad Bar Sovereign", short: "Sovereign" },
      ],
    },
    {
      id: "cucumber_cobra",
      name: "Cucumber Cobra",
      short: "Cucumber",
      rarity: "common",
      family: "salad",
      traits: ["fresh", "snack"],
      emoji: "CC",
      color: "#86c95b",
      accent: "#3f8f5a",
      hp: 24,
      atk: 10,
      speed: 0.84,
      role: "Cool Control",
      ability: "slow",
      abilityText: "Crisp bind",
      forms: [
        { name: "Cuke Hatchling", short: "Cuke" },
        { name: "Cucumber Cobra", short: "Cobra" },
        { name: "Ribbon Cucumber", short: "Ribbon" },
        { name: "Garden Coil Hydra", short: "Hydra" },
      ],
    },
    {
      id: "avocado_axolotl",
      name: "Avocado Axolotl",
      short: "Avocado",
      rarity: "uncommon",
      family: "salad",
      traits: ["fresh", "snack"],
      emoji: "AA",
      color: "#8dbb4d",
      accent: "#6f4b2f",
      hp: 36,
      atk: 8,
      speed: 1,
      role: "Pit Thorns",
      ability: "thorns",
      abilityText: "Counter hits",
      forms: [
        { name: "Avocado Totl", short: "Totl" },
        { name: "Avocado Axolotl", short: "Avo" },
        { name: "Guac Gill Axolotl", short: "Guac" },
        { name: "Orchard Pit Oracle", short: "Oracle" },
      ],
    },
    {
      id: "herb_hare",
      name: "Herb Hare",
      short: "Herb",
      rarity: "uncommon",
      family: "salad",
      traits: ["fresh", "bakery"],
      emoji: "HH",
      color: "#6fad4e",
      accent: "#d9b56f",
      hp: 30,
      atk: 8,
      speed: 1.18,
      role: "Garden Opener",
      ability: "syrup_start",
      abilityText: "Herb starter",
      forms: [
        { name: "Herb Kit", short: "Kit" },
        { name: "Herb Hare", short: "Hare" },
        { name: "Focaccia Jackrabbit", short: "Focaccia" },
        { name: "Greenhouse Jumper", short: "Jumper" },
      ],
    },
    {
      id: "green_juice_goose",
      name: "Green Juice Goose",
      short: "Juice",
      rarity: "common",
      family: "breakfast",
      traits: ["breakfast", "fresh"],
      emoji: "JG",
      color: "#8ccf2e",
      accent: "#f2c43f",
      hp: 26,
      atk: 10,
      speed: 0.9,
      role: "Garden Volley",
      ability: "back_row",
      abilityText: "Back-row juice",
      forms: [
        { name: "Juice Gosling", short: "Gosling" },
        { name: "Celery Goose", short: "Celery" },
        { name: "Garden Brunch Gander", short: "Gander" },
        { name: "Green Juice Goose", short: "Goose" },
      ],
    },
    {
      id: "caprese_capybara",
      name: "Caprese Capybara",
      short: "Caprese",
      rarity: "rare",
      family: "salad",
      traits: ["fresh", "snack"],
      emoji: "CP",
      color: "#f2f1dc",
      accent: "#d84a3a",
      hp: 42,
      atk: 8,
      speed: 1.12,
      role: "Plate Captain",
      ability: "formation_captain",
      abilityText: "Formation buff",
      forms: [
        { name: "Mozzarella Pup", short: "Mozz" },
        { name: "Caprese Capybara", short: "Caprese" },
        { name: "Basil Pond Capybara", short: "Basil" },
        { name: "Antipasto Harbour", short: "Harbour" },
      ],
    },
    {
      id: "vinaigrette_viper",
      name: "Vinaigrette Viper",
      short: "Viper",
      rarity: "epic",
      family: "salad",
      traits: ["fresh", "spicy"],
      emoji: "VV",
      color: "#d7bd45",
      accent: "#6fae48",
      hp: 28,
      atk: 12,
      speed: 0.82,
      role: "Sharp Dressing",
      ability: "status_spread",
      abilityText: "Dressing mark",
      forms: [
        { name: "Vinaigrette Viper", short: "Viper" },
        { name: "Peppercorn Viper", short: "Pepper" },
        { name: "Balsamic Coil", short: "Balsamic" },
        { name: "Dressing Dragon", short: "Dragon" },
      ],
    },
    {
      id: "kelp_koala",
      name: "Kelp Koala",
      short: "Kelp",
      rarity: "common",
      family: "salad",
      traits: ["fresh", "ocean"],
      emoji: "KK",
      color: "#4fae78",
      accent: "#2f7f83",
      hp: 28,
      atk: 8,
      speed: 1.02,
      role: "Tide Bind",
      ability: "slow",
      abilityText: "Tide bind",
      forms: [
        { name: "Kelp Joey", short: "Joey" },
        { name: "Kelp Koala", short: "Kelp" },
        { name: "Seaweed Snacker", short: "Seaweed" },
        { name: "Tide-Grove Koala", short: "Grove" },
      ],
    },
    {
      id: "melon_mint_mantis",
      name: "Melon Mint Mantis",
      short: "Melon",
      rarity: "uncommon",
      family: "fruit",
      traits: ["fresh", "sweet"],
      emoji: "MM",
      color: "#9fda6e",
      accent: "#55b89b",
      hp: 24,
      atk: 8,
      speed: 0.82,
      role: "Mint Cleanser",
      ability: "cleanse",
      abilityText: "Mint cleanse",
      forms: [
        { name: "Mint Sprout Mantis", short: "Sprout" },
        { name: "Melon Mint Mantis", short: "Melon" },
        { name: "Honeydew Blade", short: "Honeydew" },
        { name: "Melon-Grove Reaper", short: "Grove" },
      ],
    },
    {
      id: "coconut_shrimp_sheep",
      name: "Coconut Shrimp Sheep",
      short: "Coconut",
      rarity: "rare",
      family: "seafood",
      traits: ["ocean", "sweet"],
      emoji: "CS",
      color: "#f1d8aa",
      accent: "#df8f57",
      hp: 30,
      atk: 14,
      speed: 0.86,
      role: "Crisp Finisher",
      ability: "execute",
      abilityText: "Coconut finish",
      forms: [
        { name: "Coconut Lamb", short: "Lamb" },
        { name: "Coconut Shrimp Sheep", short: "Coconut" },
        { name: "Fried Fleece Shrimp", short: "Fleece" },
        { name: "Island Coconut Ram", short: "Island" },
      ],
    },
    {
      id: "crab_cake_caterpillar",
      name: "Crab Cake Caterpillar",
      short: "Crab Cake",
      rarity: "uncommon",
      family: "seafood",
      traits: ["bakery", "ocean"],
      emoji: "CC",
      color: "#d99a4f",
      accent: "#5ea3b5",
      hp: 34,
      atk: 12,
      speed: 0.98,
      role: "Shell Cracker",
      ability: "shield_breaker",
      abilityText: "Shield steal",
      forms: [
        { name: "Crumb Grub", short: "Crumb" },
        { name: "Crab Cake Caterpillar", short: "Cake" },
        { name: "Golden Shell Loaf", short: "Golden" },
        { name: "Boardwalk Crab-Cake Moth", short: "Moth" },
      ],
    },
    {
      id: "pico_de_gallo_gecko",
      name: "Pico de Gallo Gecko",
      short: "Pico",
      rarity: "common",
      family: "salsa",
      traits: ["fresh", "street_food"],
      emoji: "PG",
      color: "#d84a3a",
      accent: "#65ad52",
      hp: 26,
      atk: 12,
      speed: 0.9,
      role: "Salsa Splash",
      ability: "cleave",
      abilityText: "Pico splash",
      forms: [
        { name: "Tomato Gecko", short: "Tomato" },
        { name: "Pico de Gallo Gecko", short: "Pico" },
        { name: "Salsa Crest Gecko", short: "Salsa" },
        { name: "Market-Bowl Basilisk", short: "Market" },
      ],
    },
  ];

  const RUNTIME_SPRITES = {
    toast_tortoise: {
      1: "assets/sprites/runtime/toast-tortoise-v3/toast-tortoise_toastlet_idle_SW_00.png",
      2: "assets/sprites/runtime/toast-tortoise-v3/toast-tortoise_butterback_idle_SW_00.png",
      3: "assets/sprites/runtime/toast-tortoise-v3/toast-tortoise_clubshell_idle_SW_00.png",
      4: "assets/sprites/runtime/toast-tortoise-v3/toast-tortoise_banquet-shell_idle_SW_00.png",
    },
    sushi_seal: {
      1: "assets/sprites/runtime/sushi-seal-v3/sushi-seal_maki-pup_idle_SW_00.png",
      2: "assets/sprites/runtime/sushi-seal-v3/sushi-seal_nigiri-seal_idle_SW_00.png",
      3: "assets/sprites/runtime/sushi-seal-v3/sushi-seal_dragon-roll_idle_SW_00.png",
      4: "assets/sprites/runtime/sushi-seal-v3/sushi-seal_omakase-seal_idle_SW_00.png",
    },
    taco_tiger: {
      1: "assets/sprites/runtime/taco-tiger-v3/taco-tiger_taco-cub_idle_SW_00.png",
      2: "assets/sprites/runtime/taco-tiger-v3/taco-tiger_loaded-tiger_idle_SW_00.png",
      3: "assets/sprites/runtime/taco-tiger-v3/taco-tiger_fiesta-fang_idle_SW_00.png",
      4: "assets/sprites/runtime/taco-tiger-v3/taco-tiger_carnival-tiger_idle_SW_00.png",
    },
    berry_bat: {
      1: "assets/sprites/runtime/berry-bat-v3/berry-bat_berry-bat_idle_SW_00.png",
      2: "assets/sprites/runtime/berry-bat-v3/berry-bat_bramble-bat_idle_SW_00.png",
      3: "assets/sprites/runtime/berry-bat-v3/berry-bat_elderberry-bat_idle_SW_00.png",
      4: "assets/sprites/runtime/berry-bat-v3/berry-bat_royal-berry-bat_idle_SW_00.png",
    },
    noodle_newt: {
      1: "assets/sprites/runtime/noodle-newt-v3/noodle-newt_noodle-newt_idle_SW_00.png",
      2: "assets/sprites/runtime/noodle-newt-v3/noodle-newt_ramen-newt_idle_SW_00.png",
      3: "assets/sprites/runtime/noodle-newt-v3/noodle-newt_hotpot-newt_idle_SW_00.png",
      4: "assets/sprites/runtime/noodle-newt-v3/noodle-newt_cauldron-newt-grand-v2_idle_SW_00.png",
    },
    pancake_penguin: {
      1: "assets/sprites/runtime/pancake-penguin-v1/pancake-penguin_pancake-chick_idle_SW_00.png",
      2: "assets/sprites/runtime/pancake-penguin-v1/pancake-penguin_syrup-penguin_idle_SW_00.png",
      3: "assets/sprites/runtime/pancake-penguin-v1/pancake-penguin_stack-king_idle_SW_00.png",
      4: "assets/sprites/runtime/pancake-penguin-v1/pancake-penguin_breakfast-emperor_idle_SW_00.png",
    },
    benedict_lobster: {
      1: "assets/sprites/runtime/benedict-lobster-v3/benedict-lobster_benny-lobster_idle_SW_00.png",
      2: "assets/sprites/runtime/benedict-lobster-v3/benedict-lobster_benedict-lobster_idle_SW_00.png",
      3: "assets/sprites/runtime/benedict-lobster-v3/benedict-lobster_hollandaise-lobster_idle_SW_00.png",
      4: "assets/sprites/runtime/benedict-lobster-v3/benedict-lobster_brunch-tide-lobster_idle_SW_00.png?v=2",
    },
    pretzel_python: {
      1: "assets/sprites/runtime/pretzel-python-v1/pretzel-python_pretzel-hatchling_idle_SW_00.png",
      2: "assets/sprites/runtime/pretzel-python-v1/pretzel-python_twist-python_idle_SW_00.png",
      3: "assets/sprites/runtime/pretzel-python-v1/pretzel-python_saltcoil_idle_SW_00.png",
      4: "assets/sprites/runtime/pretzel-python-v1/pretzel-python_knot-constrictor_idle_SW_00.png",
    },
    curry_crab: {
      1: "assets/sprites/runtime/curry-crab-v1/curry-crab_curry-crab_idle_SW_00.png",
      2: "assets/sprites/runtime/curry-crab-v1/curry-crab_masala-crab_idle_SW_00.png",
      3: "assets/sprites/runtime/curry-crab-v1/curry-crab_spiceclaw_idle_SW_00.png",
      4: "assets/sprites/runtime/curry-crab-v1/curry-crab_vindaloo-titan_idle_SW_00.png",
    },
    pepper_prawn: {
      1: "assets/sprites/runtime/pepper-prawn-v1/pepper-prawn_pepper-prawn_idle_SW_00.png",
      2: "assets/sprites/runtime/pepper-prawn-v1/pepper-prawn_seared-prawn_idle_SW_00.png",
      3: "assets/sprites/runtime/pepper-prawn-v1/pepper-prawn_chili-skewer-prawn_idle_SW_00.png",
      4: "assets/sprites/runtime/pepper-prawn-v1/pepper-prawn_tidefire-prawn_idle_SW_00.png",
    },
    hot_chip_hamster: {
      1: "assets/sprites/runtime/hot-chip-hamster-v2/hot-chip-hamster_hot-chip-pup_idle_SW_00.png",
      2: "assets/sprites/runtime/hot-chip-hamster-v2/hot-chip-hamster_hot-chip-hamster_idle_SW_00.png",
      3: "assets/sprites/runtime/hot-chip-hamster-v2/hot-chip-hamster_flamin-wheel-hamster_idle_SW_00.png",
      4: "assets/sprites/runtime/hot-chip-hamster-v2/hot-chip-hamster_kettlefire-hamster_idle_SW_00.png",
    },
    popcorn_porcupine: {
      1: "assets/sprites/runtime/popcorn-porcupine-v1/popcorn-porcupine_kernel-hoglet_idle_SW_00.png",
      2: "assets/sprites/runtime/popcorn-porcupine-v1/popcorn-porcupine_popcorn-porcupine_idle_SW_00.png",
      3: "assets/sprites/runtime/popcorn-porcupine-v1/popcorn-porcupine_kettle-quillbeast_idle_SW_00.png",
      4: "assets/sprites/runtime/popcorn-porcupine-v1/popcorn-porcupine_cinema-needleback_idle_SW_00.png",
    },
    yogurt_yeti: {
      1: "assets/sprites/runtime/yogurt-yeti-v1/yogurt-yeti_yogurt-cub_idle_SW_00.png",
      2: "assets/sprites/runtime/yogurt-yeti-v1/yogurt-yeti_parfait-yeti_idle_SW_00.png",
      3: "assets/sprites/runtime/yogurt-yeti-v1/yogurt-yeti_frozen-yeti_idle_SW_00.png",
      4: "assets/sprites/runtime/yogurt-yeti-v1/yogurt-yeti_glacier-parfait_idle_SW_00.png",
    },
    donut_dodo: {
      1: "assets/sprites/runtime/donut-dodo-v1/donut-dodo_donut-dodo_idle_SW_00.png",
      2: "assets/sprites/runtime/donut-dodo-v1/donut-dodo_glazed-dodo_idle_SW_00.png",
      3: "assets/sprites/runtime/donut-dodo-v1/donut-dodo_sprinkle-roc_idle_SW_00.png",
      4: "assets/sprites/runtime/donut-dodo-v1/donut-dodo_bakery-phoenix_idle_SW_00.png",
    },
    kimchi_chameleon: {
      1: "assets/sprites/runtime/kimchi-chameleon-v1/kimchi-chameleon_kimchi-chameleon_idle_SW_00.png",
      2: "assets/sprites/runtime/kimchi-chameleon-v1/kimchi-chameleon_ferment-gecko_idle_SW_00.png",
      3: "assets/sprites/runtime/kimchi-chameleon-v1/kimchi-chameleon_gochu-chameleon_idle_SW_00.png",
      4: "assets/sprites/runtime/kimchi-chameleon-v1/kimchi-chameleon_pickled-dragon_idle_SW_00.png",
    },
    waffle_walrus: {
      1: "assets/sprites/runtime/waffle-walrus-v1/waffle-walrus_waffle-pup_idle_SW_00.png",
      2: "assets/sprites/runtime/waffle-walrus-v1/waffle-walrus_waffle-walrus_idle_SW_00.png",
      3: "assets/sprites/runtime/waffle-walrus-v1/waffle-walrus_syrup-tusk-walrus_idle_SW_00.png",
      4: "assets/sprites/runtime/waffle-walrus-v1/waffle-walrus_brunch-behemoth_idle_SW_00.png",
    },
    dumpling_armadillo: {
      1: "assets/sprites/runtime/dumpling-armadillo-v1/dumpling-armadillo_dumpling-dillo_idle_SW_00.png",
      2: "assets/sprites/runtime/dumpling-armadillo-v1/dumpling-armadillo_bao-armadillo_idle_SW_00.png",
      3: "assets/sprites/runtime/dumpling-armadillo-v1/dumpling-armadillo_dim-sum-dozer_idle_SW_00.png",
      4: "assets/sprites/runtime/dumpling-armadillo-v1/dumpling-armadillo_steam-basket-bastion_idle_SW_00.png",
    },
    bagel_beaver: {
      1: "assets/sprites/runtime/bagel-beaver-v1/bagel-beaver_bagel-beaver_idle_SW_00.png",
      2: "assets/sprites/runtime/bagel-beaver-v1/bagel-beaver_sesame-beaver_idle_SW_00.png",
      3: "assets/sprites/runtime/bagel-beaver-v1/bagel-beaver_everything-dam-beaver_idle_SW_00.png",
      4: "assets/sprites/runtime/bagel-beaver-v1/bagel-beaver_brunch-lodge-beaver_idle_SW_00.png",
    },
    bao_bun_badger: {
      1: "assets/sprites/runtime/bao-bun-badger-v1/bao-bun-badger_bao-bun-badger_idle_SW_00.png",
      2: "assets/sprites/runtime/bao-bun-badger-v1/bao-bun-badger_sesame-bao-badger_idle_SW_00.png",
      3: "assets/sprites/runtime/bao-bun-badger-v1/bao-bun-badger_steam-cart-badger_idle_SW_00.png",
      4: "assets/sprites/runtime/bao-bun-badger-v1/bao-bun-badger_night-market-bao-boss_idle_SW_00.png",
    },
    lemon_meringue_lynx: {
      1: "assets/sprites/runtime/lemon-meringue-lynx-v1/lemon-meringue-lynx_lemon-lynx_idle_SW_00.png",
      2: "assets/sprites/runtime/lemon-meringue-lynx-v1/lemon-meringue-lynx_meringue-lynx_idle_SW_00.png",
      3: "assets/sprites/runtime/lemon-meringue-lynx-v1/lemon-meringue-lynx_tart-panther_idle_SW_00.png",
      4: "assets/sprites/runtime/lemon-meringue-lynx-v1/lemon-meringue-lynx_citrus-sphinx_idle_SW_00.png",
    },
    shakshuka_shark: {
      1: "assets/sprites/runtime/shakshuka-shark-v1/shakshuka-shark_shakshuka-shark_idle_SW_00.png",
      2: "assets/sprites/runtime/shakshuka-shark-v1/shakshuka-shark_saucy-shark_idle_SW_00.png",
      3: "assets/sprites/runtime/shakshuka-shark-v1/shakshuka-shark_skilletfin-shark_idle_SW_00.png",
      4: "assets/sprites/runtime/shakshuka-shark-v1/shakshuka-shark_harissa-megalodon_idle_SW_00.png",
    },
    saltwater_taffy_otter: {
      1: "assets/sprites/runtime/saltwater-taffy-otter-v1/saltwater-taffy-otter_taffy-pup_idle_SW_00.png",
      2: "assets/sprites/runtime/saltwater-taffy-otter-v1/saltwater-taffy-otter_saltwater-taffy-otter_idle_SW_00.png",
      3: "assets/sprites/runtime/saltwater-taffy-otter-v1/saltwater-taffy-otter_ribbon-taffy-otter_idle_SW_00.png",
      4: "assets/sprites/runtime/saltwater-taffy-otter-v1/saltwater-taffy-otter_candy-tide-otter_idle_SW_00.png",
    },
    croissant_kraken: {
      1: "assets/sprites/runtime/croissant-kraken-v1/croissant-kraken_croissant-squid_idle_SW_00.png",
      2: "assets/sprites/runtime/croissant-kraken-v1/croissant-kraken_buttered-kraken_idle_SW_00.png",
      3: "assets/sprites/runtime/croissant-kraken-v1/croissant-kraken_laminated-leviathan_idle_SW_00.png",
      4: "assets/sprites/runtime/croissant-kraken-v1/croissant-kraken_thousand-layer-abyss_idle_SW_00.png",
    },
    fortune_cookie_fox: {
      1: "assets/sprites/runtime/fortune-cookie-fox-v1/fortune-cookie-fox_fortune-kit_idle_SW_00.png",
      2: "assets/sprites/runtime/fortune-cookie-fox-v1/fortune-cookie-fox_cookie-fox_idle_SW_00.png",
      3: "assets/sprites/runtime/fortune-cookie-fox-v1/fortune-cookie-fox_prophecy-vixen_idle_SW_00.png",
      4: "assets/sprites/runtime/fortune-cookie-fox-v1/fortune-cookie-fox_oracle-kitsune_idle_SW_00.png",
    },
    mochi_mammoth: {
      1: "assets/sprites/runtime/mochi-mammoth-v1/mochi-mammoth_mochi-calf_idle_SW_00.png",
      2: "assets/sprites/runtime/mochi-mammoth-v1/mochi-mammoth_mochi-mammoth_idle_SW_00.png",
      3: "assets/sprites/runtime/mochi-mammoth-v1/mochi-mammoth_mooncake-mastodon_idle_SW_00.png",
      4: "assets/sprites/runtime/mochi-mammoth-v1/mochi-mammoth_festival-colossus_idle_SW_00.png",
    },
    gingerbread_golem: {
      1: "assets/sprites/runtime/gingerbread-golem-v1/gingerbread-golem_gingerling_idle_SW_00.png",
      2: "assets/sprites/runtime/gingerbread-golem-v1/gingerbread-golem_gingerbread-golem_idle_SW_00.png",
      3: "assets/sprites/runtime/gingerbread-golem-v1/gingerbread-golem_frosted-guardian_idle_SW_00.png",
      4: "assets/sprites/runtime/gingerbread-golem-v1/gingerbread-golem_candy-castle-colossus_idle_SW_00.png",
    },
    boba_basilisk: {
      1: "assets/sprites/runtime/boba-basilisk-v1/boba-basilisk_boba-newt_idle_SW_00.png",
      2: "assets/sprites/runtime/boba-basilisk-v1/boba-basilisk_tapioca-basilisk_idle_SW_00.png",
      3: "assets/sprites/runtime/boba-basilisk-v1/boba-basilisk_pearl-gorgon_idle_SW_00.png",
      4: "assets/sprites/runtime/boba-basilisk-v1/boba-basilisk_bubble-tea-hydra_idle_SW_00.png",
    },
    iceberg_oyster: {
      1: "assets/sprites/runtime/iceberg-oyster-v2/iceberg-oyster_iceberg-oyster_idle_SW_00.png",
      2: "assets/sprites/runtime/iceberg-oyster-v2/iceberg-oyster_pearl-ice-oyster_idle_SW_00.png",
      3: "assets/sprites/runtime/iceberg-oyster-v2/iceberg-oyster_glacier-shell-oyster_idle_SW_00.png",
      4: "assets/sprites/runtime/iceberg-oyster-v2/iceberg-oyster_abyssal-ice-pearl_idle_SW_00.png",
    },
    churro_cheetah: {
      1: "assets/sprites/runtime/churro-cheetah-v1/churro-cheetah_churro-cub_idle_SW_00.png",
      2: "assets/sprites/runtime/churro-cheetah-v1/churro-cheetah_cinnamon-cheetah_idle_SW_00.png",
      3: "assets/sprites/runtime/churro-cheetah-v1/churro-cheetah_chili-churro-cheetah_idle_SW_00.png",
      4: "assets/sprites/runtime/churro-cheetah-v1/churro-cheetah_dulce-firecat-v2_idle_SW_00.png",
    },
    granola_goat: {
      1: "assets/sprites/runtime/granola-goat-v1/granola-goat_oat-kid_idle_SW_00.png",
      2: "assets/sprites/runtime/granola-goat-v1/granola-goat_granola-goat_idle_SW_00.png",
      3: "assets/sprites/runtime/granola-goat-v1/granola-goat_trail-mix-ram-v3_idle_SW_00.png",
      4: "assets/sprites/runtime/granola-goat-v1/granola-goat_harvest-ibex-v3_idle_SW_00.png",
    },
    breakfast_burrito_boar: {
      1: "assets/sprites/runtime/breakfast-burrito-boar-v1/breakfast-burrito-boar_egg-wrap-piglet_idle_SW_00.png",
      2: "assets/sprites/runtime/breakfast-burrito-boar-v1/breakfast-burrito-boar_breakfast-burrito-boar_idle_SW_00.png",
      3: "assets/sprites/runtime/breakfast-burrito-boar-v1/breakfast-burrito-boar_salsa-tusk-boar_idle_SW_00.png",
      4: "assets/sprites/runtime/breakfast-burrito-boar-v1/breakfast-burrito-boar_brunch-cart-boar_idle_SW_00.png",
    },
    caesar_salamander: {
      1: "assets/sprites/runtime/caesar-salamander-v1/caesar-salamander_romaine-newt_idle_SW_00.png",
      2: "assets/sprites/runtime/caesar-salamander-v1/caesar-salamander_caesar-salamander_idle_SW_00.png",
      3: "assets/sprites/runtime/caesar-salamander-v1/caesar-salamander_crouton-crest_idle_SW_00.png",
      4: "assets/sprites/runtime/caesar-salamander-v1/caesar-salamander_salad-bar-sovereign_idle_SW_00.png",
    },
    cucumber_cobra: {
      1: "assets/sprites/runtime/cucumber-cobra-v1/cucumber-cobra_cuke-hatchling_idle_SW_00.png",
      2: "assets/sprites/runtime/cucumber-cobra-v1/cucumber-cobra_cucumber-cobra_idle_SW_00.png",
      3: "assets/sprites/runtime/cucumber-cobra-v1/cucumber-cobra_ribbon-cucumber_idle_SW_00.png",
      4: "assets/sprites/runtime/cucumber-cobra-v1/cucumber-cobra_garden-coil-hydra_idle_SW_00.png",
    },
    avocado_axolotl: {
      1: "assets/sprites/runtime/avocado-axolotl-v1/avocado-axolotl_avocado-totl_idle_SW_00.png",
      2: "assets/sprites/runtime/avocado-axolotl-v1/avocado-axolotl_avocado-axolotl_idle_SW_00.png",
      3: "assets/sprites/runtime/avocado-axolotl-v1/avocado-axolotl_guac-gill-axolotl_idle_SW_00.png",
      4: "assets/sprites/runtime/avocado-axolotl-v1/avocado-axolotl_orchard-pit-oracle_idle_SW_00.png",
    },
    herb_hare: {
      1: "assets/sprites/runtime/herb-hare-v1/herb-hare_herb-kit_idle_SW_00.png",
      2: "assets/sprites/runtime/herb-hare-v1/herb-hare_herb-hare_idle_SW_00.png",
      3: "assets/sprites/runtime/herb-hare-v1/herb-hare_focaccia-jackrabbit_idle_SW_00.png",
      4: "assets/sprites/runtime/herb-hare-v1/herb-hare_greenhouse-jumper_idle_SW_00.png",
    },
    green_juice_goose: {
      1: "assets/sprites/runtime/green-juice-goose-v1/green-juice-goose_juice-gosling_idle_SW_00.png",
      2: "assets/sprites/runtime/green-juice-goose-v1/green-juice-goose_celery-goose_idle_SW_00.png",
      3: "assets/sprites/runtime/green-juice-goose-v1/green-juice-goose_garden-brunch-gander_idle_SW_00.png",
      4: "assets/sprites/runtime/green-juice-goose-v1/green-juice-goose_green-juice-goose_idle_SW_00.png",
    },
    caprese_capybara: {
      1: "assets/sprites/runtime/caprese-capybara-v1/caprese-capybara_mozzarella-pup_idle_SW_00.png",
      2: "assets/sprites/runtime/caprese-capybara-v1/caprese-capybara_caprese-capybara_idle_SW_00.png",
      3: "assets/sprites/runtime/caprese-capybara-v2/caprese-capybara_basil-pond-capybara_idle_SW_00.png",
      4: "assets/sprites/runtime/caprese-capybara-v2/caprese-capybara_antipasto-harbour_idle_SW_00.png",
    },
    vinaigrette_viper: {
      1: "assets/sprites/runtime/vinaigrette-viper-v1/vinaigrette-viper_vinaigrette-viper_idle_SW_00.png",
      2: "assets/sprites/runtime/vinaigrette-viper-v1/vinaigrette-viper_peppercorn-viper_idle_SW_00.png",
      3: "assets/sprites/runtime/vinaigrette-viper-v1/vinaigrette-viper_balsamic-coil_idle_SW_00.png",
      4: "assets/sprites/runtime/vinaigrette-viper-v1/vinaigrette-viper_dressing-dragon_idle_SW_00.png",
    },
    kelp_koala: {
      1: "assets/sprites/runtime/kelp-koala-v2/kelp-koala_kelp-joey_idle_SW_00.png",
      2: "assets/sprites/runtime/kelp-koala-v2/kelp-koala_kelp-koala_idle_SW_00.png",
      3: "assets/sprites/runtime/kelp-koala-v2/kelp-koala_seaweed-snacker_idle_SW_00.png",
      4: "assets/sprites/runtime/kelp-koala-v2/kelp-koala_tide-grove-koala_idle_SW_00.png",
    },
    melon_mint_mantis: {
      1: "assets/sprites/runtime/melon-mint-mantis-v2/melon-mint-mantis_mint-sprout-mantis_idle_SW_00.png",
      2: "assets/sprites/runtime/melon-mint-mantis-v2/melon-mint-mantis_melon-mint-mantis_idle_SW_00.png",
      3: "assets/sprites/runtime/melon-mint-mantis-v2/melon-mint-mantis_honeydew-blade_idle_SW_00.png",
      4: "assets/sprites/runtime/melon-mint-mantis-v2/melon-mint-mantis_melon-grove-reaper_idle_SW_00.png",
    },
    coconut_shrimp_sheep: {
      1: "assets/sprites/runtime/coconut-shrimp-sheep-v3/coconut-shrimp-sheep_coconut-lamb_idle_SW_00.png",
      2: "assets/sprites/runtime/coconut-shrimp-sheep-v3/coconut-shrimp-sheep_coconut-shrimp-sheep_idle_SW_00.png",
      3: "assets/sprites/runtime/coconut-shrimp-sheep-v3/coconut-shrimp-sheep_fried-fleece-shrimp_idle_SW_00.png",
      4: "assets/sprites/runtime/coconut-shrimp-sheep-v3/coconut-shrimp-sheep_island-coconut-ram_idle_SW_00.png",
    },
    crab_cake_caterpillar: {
      1: "assets/sprites/runtime/crab-cake-caterpillar-v2/crab-cake-caterpillar_crumb-grub_idle_SW_00.png",
      2: "assets/sprites/runtime/crab-cake-caterpillar-v2/crab-cake-caterpillar_crab-cake-caterpillar_idle_SW_00.png",
      3: "assets/sprites/runtime/crab-cake-caterpillar-v2/crab-cake-caterpillar_golden-shell-loaf_idle_SW_00.png",
      4: "assets/sprites/runtime/crab-cake-caterpillar-v2/crab-cake-caterpillar_boardwalk-crab-cake-moth_idle_SW_00.png",
    },
    pico_de_gallo_gecko: {
      1: "assets/sprites/runtime/pico-de-gallo-gecko-v3/pico-de-gallo-gecko_tomato-gecko_idle_SW_00.png",
      2: "assets/sprites/runtime/pico-de-gallo-gecko-v3/pico-de-gallo-gecko_pico-de-gallo-gecko_idle_SW_00.png",
      3: "assets/sprites/runtime/pico-de-gallo-gecko-v3/pico-de-gallo-gecko_salsa-crest-gecko_idle_SW_00.png",
      4: "assets/sprites/runtime/pico-de-gallo-gecko-v3/pico-de-gallo-gecko_market-bowl-basilisk_idle_SW_00.png",
    },
    "banana_split_giraffe_boss": {
      1: "assets/sprites/runtime/banana-split-giraffe-boss-v2/banana-split-giraffe-boss_banana-split-giraffe-boss-high-detail_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/banana-split-giraffe-boss-v2/banana-split-giraffe-boss_banana-split-giraffe-boss-high-detail_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/banana-split-giraffe-boss-v2/banana-split-giraffe-boss_banana-split-giraffe-boss-high-detail_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/banana-split-giraffe-boss-v2/banana-split-giraffe-boss_banana-split-giraffe-boss-high-detail_idle_SW_00.png?v=1",
    },
  };
  const REALITY_RUNTIME_SPRITES = {
    toast_tortoise: {
      1: "assets/sprites/runtime/war-machine-toast-tortoise-v4/toast_tortoise-bulwark-siege-tank-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-toast-tortoise-v4/toast_tortoise-bulwark-siege-tank-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-toast-tortoise-v4/toast_tortoise-bulwark-siege-tank-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-toast-tortoise-v4/toast_tortoise-bulwark-siege-tank-mk4_idle_SW_00.png?v=1",
    },
    sushi_seal: {
      1: "assets/sprites/runtime/war-machine-sushi-seal-v2/sushi_seal-tide-recon-drone-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-sushi-seal-v2/sushi_seal-tide-recon-drone-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-sushi-seal-v2/sushi_seal-tide-recon-drone-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-sushi-seal-v2/sushi_seal-tide-recon-drone-mk4_idle_SW_00.png?v=1",
    },
    taco_tiger: {
      1: "assets/sprites/runtime/war-machine-taco-tiger-v3/taco_tiger-shellbreaker-assault-rig-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-taco-tiger-v3/taco_tiger-shellbreaker-assault-rig-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-taco-tiger-v3/taco_tiger-shellbreaker-assault-rig-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-taco-tiger-v3/taco_tiger-shellbreaker-assault-rig-mk4_idle_SW_00.png?v=1",
    },
    berry_bat: {
      1: "assets/sprites/runtime/war-machine-berry-bat-v1/berry_bat-nightwing-swarm-drone-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-berry-bat-v1/berry_bat-nightwing-swarm-drone-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-berry-bat-v1/berry_bat-nightwing-swarm-drone-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-berry-bat-v1/berry_bat-nightwing-swarm-drone-mk4_idle_SW_00.png?v=1",
    },
    noodle_newt: {
      1: "assets/sprites/runtime/war-machine-noodle-newt-v3/noodle_newt-serpent-medic-rig-mk1_idle_SW_00.png?v=3",
      2: "assets/sprites/runtime/war-machine-noodle-newt-v3/noodle_newt-serpent-medic-rig-mk2_idle_SW_00.png?v=3",
      3: "assets/sprites/runtime/war-machine-noodle-newt-v3/noodle_newt-serpent-medic-rig-mk3_idle_SW_00.png?v=3",
      4: "assets/sprites/runtime/war-machine-noodle-newt-v3/noodle_newt-serpent-medic-rig-mk4_idle_SW_00.png?v=3",
    },
    pancake_penguin: {
      1: "assets/sprites/runtime/war-machine-pancake-penguin-v1/pancake_penguin-dawn-shield-walker-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-pancake-penguin-v1/pancake_penguin-dawn-shield-walker-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-pancake-penguin-v1/pancake_penguin-dawn-shield-walker-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-pancake-penguin-v1/pancake_penguin-dawn-shield-walker-mk4_idle_SW_00.png?v=1",
    },
    pretzel_python: {
      1: "assets/sprites/runtime/war-machine-pretzel-python-v1/pretzel_python-knotwire-serpent-engine-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-pretzel-python-v1/pretzel_python-knotwire-serpent-engine-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-pretzel-python-v1/pretzel_python-knotwire-serpent-engine-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-pretzel-python-v1/pretzel_python-knotwire-serpent-engine-mk4_idle_SW_00.png?v=1",
    },
    popcorn_porcupine: {
      1: "assets/sprites/runtime/war-machine-popcorn-porcupine-v2/popcorn_porcupine-shrapnel-quill-battery-mk1_idle_SW_00.png?v=2",
      2: "assets/sprites/runtime/war-machine-popcorn-porcupine-v2/popcorn_porcupine-shrapnel-quill-battery-mk2_idle_SW_00.png?v=2",
      3: "assets/sprites/runtime/war-machine-popcorn-porcupine-v2/popcorn_porcupine-shrapnel-quill-battery-mk3_idle_SW_00.png?v=2",
      4: "assets/sprites/runtime/war-machine-popcorn-porcupine-v2/popcorn_porcupine-shrapnel-quill-battery-mk4_idle_SW_00.png?v=2",
    },
    yogurt_yeti: {
      1: "assets/sprites/runtime/war-machine-yogurt-yeti-v2/yogurt_yeti-cryo-support-golem-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-yogurt-yeti-v2/yogurt_yeti-cryo-support-golem-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-yogurt-yeti-v2/yogurt_yeti-cryo-support-golem-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-yogurt-yeti-v2/yogurt_yeti-cryo-support-golem-mk4_idle_SW_00.png?v=1",
    },
    bagel_beaver: {
      1: "assets/sprites/runtime/war-machine-bagel-beaver-v2/bagel_beaver-foundry-dam-engine-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-bagel-beaver-v2/bagel_beaver-foundry-dam-engine-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-bagel-beaver-v2/bagel_beaver-foundry-dam-engine-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-bagel-beaver-v2/bagel_beaver-foundry-dam-engine-mk4_idle_SW_00.png?v=1",
    },
    bao_bun_badger: {
      1: "assets/sprites/runtime/war-machine-bao-bun-badger-v1/bao_bun_badger-steamcart-bulwark-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-bao-bun-badger-v1/bao_bun_badger-steamcart-bulwark-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-bao-bun-badger-v1/bao_bun_badger-steamcart-bulwark-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-bao-bun-badger-v1/bao_bun_badger-steamcart-bulwark-mk4_idle_SW_00.png?v=1",
    },
    donut_dodo: {
      1: "assets/sprites/runtime/war-machine-donut-dodo-v2/donut_dodo-phoenix-scrap-bomber-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-donut-dodo-v2/donut_dodo-phoenix-scrap-bomber-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-donut-dodo-v2/donut_dodo-phoenix-scrap-bomber-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-donut-dodo-v2/donut_dodo-phoenix-scrap-bomber-mk4_idle_SW_00.png?v=1",
    },
    kimchi_chameleon: {
      1: "assets/sprites/runtime/war-machine-kimchi-chameleon-v1/kimchi_chameleon-ferment-camo-unit-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-kimchi-chameleon-v1/kimchi_chameleon-ferment-camo-unit-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-kimchi-chameleon-v1/kimchi_chameleon-ferment-camo-unit-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-kimchi-chameleon-v1/kimchi_chameleon-ferment-camo-unit-mk4_idle_SW_00.png?v=1",
    },
    waffle_walrus: {
      1: "assets/sprites/runtime/war-machine-waffle-walrus-v3/waffle_walrus-syrup-tusk-siege-engine-mk1_idle_SW_00.png?v=3",
      2: "assets/sprites/runtime/war-machine-waffle-walrus-v3/waffle_walrus-syrup-tusk-siege-engine-mk2_idle_SW_00.png?v=3",
      3: "assets/sprites/runtime/war-machine-waffle-walrus-v3/waffle_walrus-syrup-tusk-siege-engine-mk3_idle_SW_00.png?v=3",
      4: "assets/sprites/runtime/war-machine-waffle-walrus-v3/waffle_walrus-syrup-tusk-siege-engine-mk4_idle_SW_00.png?v=3",
    },
    dumpling_armadillo: {
      1: "assets/sprites/runtime/war-machine-dumpling-armadillo-v3/dumpling_armadillo-steam-bastion-dozer-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-dumpling-armadillo-v3/dumpling_armadillo-steam-bastion-dozer-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-dumpling-armadillo-v3/dumpling_armadillo-steam-bastion-dozer-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-dumpling-armadillo-v3/dumpling_armadillo-steam-bastion-dozer-mk4_idle_SW_00.png?v=1",
    },
    lemon_meringue_lynx: {
      1: "assets/sprites/runtime/war-machine-lemon-meringue-lynx-v3/lemon_meringue_lynx-acid-cleanser-stalker-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-lemon-meringue-lynx-v3/lemon_meringue_lynx-acid-cleanser-stalker-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-lemon-meringue-lynx-v3/lemon_meringue_lynx-acid-cleanser-stalker-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-lemon-meringue-lynx-v3/lemon_meringue_lynx-acid-cleanser-stalker-mk4_idle_SW_00.png?v=1",
    },
    shakshuka_shark: {
      1: "assets/sprites/runtime/war-machine-shakshuka-shark-v4/shakshuka_shark-thermal-megalodon-subtank-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-shakshuka-shark-v4/shakshuka_shark-thermal-megalodon-subtank-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-shakshuka-shark-v4/shakshuka_shark-thermal-megalodon-subtank-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-shakshuka-shark-v4/shakshuka_shark-thermal-megalodon-subtank-mk4_idle_SW_00.png?v=1",
    },
    saltwater_taffy_otter: {
      1: "assets/sprites/runtime/war-machine-saltwater-taffy-otter-v3/saltwater_taffy_otter-tide-bind-strider-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-saltwater-taffy-otter-v3/saltwater_taffy_otter-tide-bind-strider-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-saltwater-taffy-otter-v3/saltwater_taffy_otter-tide-bind-strider-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-saltwater-taffy-otter-v3/saltwater_taffy_otter-tide-bind-strider-mk4_idle_SW_00.png?v=1",
    },
    croissant_kraken: {
      1: "assets/sprites/runtime/war-machine-croissant-kraken-v3/croissant_kraken-layered-leviathan-rig-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-croissant-kraken-v3/croissant_kraken-layered-leviathan-rig-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-croissant-kraken-v3/croissant_kraken-layered-leviathan-rig-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-croissant-kraken-v3/croissant_kraken-layered-leviathan-rig-mk4_idle_SW_00.png?v=1",
    },
    fortune_cookie_fox: {
      1: "assets/sprites/runtime/war-machine-fortune-cookie-fox-v3/fortune_cookie_fox-oracle-chance-engine-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-fortune-cookie-fox-v3/fortune_cookie_fox-oracle-chance-engine-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-fortune-cookie-fox-v3/fortune_cookie_fox-oracle-chance-engine-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-fortune-cookie-fox-v3/fortune_cookie_fox-oracle-chance-engine-mk4_idle_SW_00.png?v=1",
    },
    mochi_mammoth: {
      1: "assets/sprites/runtime/war-machine-mochi-mammoth-v4/mochi_mammoth-festival-colossus-walker-mk1_idle_SW_00.png?v=4",
      2: "assets/sprites/runtime/war-machine-mochi-mammoth-v4/mochi_mammoth-festival-colossus-walker-mk2_idle_SW_00.png?v=4",
      3: "assets/sprites/runtime/war-machine-mochi-mammoth-v4/mochi_mammoth-festival-colossus-walker-mk3_idle_SW_00.png?v=4",
      4: "assets/sprites/runtime/war-machine-mochi-mammoth-v4/mochi_mammoth-festival-colossus-walker-mk4_idle_SW_00.png?v=4",
    },
    gingerbread_golem: {
      1: "assets/sprites/runtime/war-machine-gingerbread-golem-v3/gingerbread_golem-citadel-decoy-guardian-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-gingerbread-golem-v3/gingerbread_golem-citadel-decoy-guardian-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-gingerbread-golem-v3/gingerbread_golem-citadel-decoy-guardian-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-gingerbread-golem-v3/gingerbread_golem-citadel-decoy-guardian-mk4_idle_SW_00.png?v=1",
    },
    boba_basilisk: {
      1: "assets/sprites/runtime/war-machine-boba-basilisk-v5/boba_basilisk-pearl-gorgon-artillery-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-boba-basilisk-v5/boba_basilisk-pearl-gorgon-artillery-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-boba-basilisk-v5/boba_basilisk-pearl-gorgon-artillery-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-boba-basilisk-v5/boba_basilisk-pearl-gorgon-artillery-mk4_idle_SW_00.png?v=1",
    },
    iceberg_oyster: {
      1: "assets/sprites/runtime/war-machine-iceberg-oyster-v4/iceberg_oyster-abyssal-lock-core-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-iceberg-oyster-v4/iceberg_oyster-abyssal-lock-core-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-iceberg-oyster-v4/iceberg_oyster-abyssal-lock-core-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-iceberg-oyster-v4/iceberg_oyster-abyssal-lock-core-mk4_idle_SW_00.png?v=1",
    },
    herb_hare: {
      1: "assets/sprites/runtime/war-machine-herb-hare-v2/herb_hare-greenhouse-jumper-rig-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-herb-hare-v2/herb_hare-greenhouse-jumper-rig-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-herb-hare-v2/herb_hare-greenhouse-jumper-rig-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-herb-hare-v2/herb_hare-greenhouse-jumper-rig-mk4_idle_SW_00.png?v=1",
    },
    green_juice_goose: {
      1: "assets/sprites/runtime/war-machine-green-juice-goose-v2/green_juice_goose-garden-volley-gunship-mk1_idle_SW_00.png?v=2",
      2: "assets/sprites/runtime/war-machine-green-juice-goose-v2/green_juice_goose-garden-volley-gunship-mk2_idle_SW_00.png?v=2",
      3: "assets/sprites/runtime/war-machine-green-juice-goose-v2/green_juice_goose-garden-volley-gunship-mk3_idle_SW_00.png?v=2",
      4: "assets/sprites/runtime/war-machine-green-juice-goose-v2/green_juice_goose-garden-volley-gunship-mk4_idle_SW_00.png?v=2",
    },
    caprese_capybara: {
      1: "assets/sprites/runtime/war-machine-caprese-capybara-v1/caprese_capybara-antipasto-harbor-platform-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-caprese-capybara-v1/caprese_capybara-antipasto-harbor-platform-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-caprese-capybara-v1/caprese_capybara-antipasto-harbor-platform-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-caprese-capybara-v1/caprese_capybara-antipasto-harbor-platform-mk4_idle_SW_00.png?v=1",
    },
    vinaigrette_viper: {
      1: "assets/sprites/runtime/war-machine-vinaigrette-viper-v1/vinaigrette_viper-dressing-dragon-coil-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-vinaigrette-viper-v1/vinaigrette_viper-dressing-dragon-coil-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-vinaigrette-viper-v1/vinaigrette_viper-dressing-dragon-coil-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-vinaigrette-viper-v1/vinaigrette_viper-dressing-dragon-coil-mk4_idle_SW_00.png?v=1",
    },
    kelp_koala: {
      1: "assets/sprites/runtime/war-machine-kelp-koala-v2/kelp_koala-tide-grove-lock-drone-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-kelp-koala-v2/kelp_koala-tide-grove-lock-drone-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-kelp-koala-v2/kelp_koala-tide-grove-lock-drone-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-kelp-koala-v2/kelp_koala-tide-grove-lock-drone-mk4_idle_SW_00.png?v=1",
    },
    melon_mint_mantis: {
      1: "assets/sprites/runtime/war-machine-melon-mint-mantis-v1/melon_mint_mantis-melon-grove-reaper-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-melon-mint-mantis-v1/melon_mint_mantis-melon-grove-reaper-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-melon-mint-mantis-v1/melon_mint_mantis-melon-grove-reaper-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-melon-mint-mantis-v1/melon_mint_mantis-melon-grove-reaper-mk4_idle_SW_00.png?v=1",
    },
    coconut_shrimp_sheep: {
      1: "assets/sprites/runtime/war-machine-coconut-shrimp-sheep-v1/coconut_shrimp_sheep-island-ram-artillery-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-coconut-shrimp-sheep-v1/coconut_shrimp_sheep-island-ram-artillery-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-coconut-shrimp-sheep-v1/coconut_shrimp_sheep-island-ram-artillery-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-coconut-shrimp-sheep-v1/coconut_shrimp_sheep-island-ram-artillery-mk4_idle_SW_00.png?v=1",
    },
    crab_cake_caterpillar: {
      1: "assets/sprites/runtime/war-machine-crab-cake-caterpillar-v1/crab_cake_caterpillar-boardwalk-moth-tank-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-crab-cake-caterpillar-v1/crab_cake_caterpillar-boardwalk-moth-tank-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-crab-cake-caterpillar-v1/crab_cake_caterpillar-boardwalk-moth-tank-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-crab-cake-caterpillar-v1/crab_cake_caterpillar-boardwalk-moth-tank-mk4_idle_SW_00.png?v=1",
    },
    pico_de_gallo_gecko: {
      1: "assets/sprites/runtime/war-machine-pico-de-gallo-gecko-v1/pico_de_gallo_gecko-market-bowl-basilisk-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-pico-de-gallo-gecko-v1/pico_de_gallo_gecko-market-bowl-basilisk-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-pico-de-gallo-gecko-v1/pico_de_gallo_gecko-market-bowl-basilisk-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-pico-de-gallo-gecko-v1/pico_de_gallo_gecko-market-bowl-basilisk-mk4_idle_SW_00.png?v=1",
    },
    pepper_prawn: {
      1: "assets/sprites/runtime/war-machine-pepper-prawn-v1/pepper_prawn-tidefire-assault-skimmer-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-pepper-prawn-v1/pepper_prawn-tidefire-assault-skimmer-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-pepper-prawn-v1/pepper_prawn-tidefire-assault-skimmer-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-pepper-prawn-v1/pepper_prawn-tidefire-assault-skimmer-mk4_idle_SW_00.png?v=1",
    },
    hot_chip_hamster: {
      1: "assets/sprites/runtime/war-machine-hot-chip-hamster-v3/hot_chip_hamster-kettlefire-wheel-rig-mk1_idle_SW_00.png?v=3",
      2: "assets/sprites/runtime/war-machine-hot-chip-hamster-v3/hot_chip_hamster-kettlefire-wheel-rig-mk2_idle_SW_00.png?v=3",
      3: "assets/sprites/runtime/war-machine-hot-chip-hamster-v3/hot_chip_hamster-kettlefire-wheel-rig-mk3_idle_SW_00.png?v=3",
      4: "assets/sprites/runtime/war-machine-hot-chip-hamster-v3/hot_chip_hamster-kettlefire-wheel-rig-mk4_idle_SW_00.png?v=3",
    },
    benedict_lobster: {
      1: "assets/sprites/runtime/war-machine-benedict-lobster-v2/benedict_lobster-brunch-breaker-siege-rig-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-benedict-lobster-v2/benedict_lobster-brunch-breaker-siege-rig-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-benedict-lobster-v2/benedict_lobster-brunch-breaker-siege-rig-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-benedict-lobster-v2/benedict_lobster-brunch-breaker-siege-rig-mk4_idle_SW_00.png?v=1",
    },
    curry_crab: {
      1: "assets/sprites/runtime/war-machine-curry-crab-v1/curry_crab-vindaloo-breaker-tank-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-curry-crab-v1/curry_crab-vindaloo-breaker-tank-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-curry-crab-v1/curry_crab-vindaloo-breaker-tank-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-curry-crab-v1/curry_crab-vindaloo-breaker-tank-mk4_idle_SW_00.png?v=1",
    },
    churro_cheetah: {
      1: "assets/sprites/runtime/war-machine-churro-cheetah-v2/churro_cheetah_dulce-striker-rig-mk1_idle_SW_00.png?v=3",
      2: "assets/sprites/runtime/war-machine-churro-cheetah-v2/churro_cheetah_dulce-striker-rig-mk2_idle_SW_00.png?v=3",
      3: "assets/sprites/runtime/war-machine-churro-cheetah-v2/churro_cheetah_dulce-striker-rig-mk3_idle_SW_00.png?v=3",
      4: "assets/sprites/runtime/war-machine-churro-cheetah-v2/churro_cheetah_dulce-striker-rig-mk4_idle_SW_00.png?v=3",
    },
    granola_goat: {
      1: "assets/sprites/runtime/war-machine-granola-goat-v1/granola_goat-harvest-ibex-walker-mk1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-granola-goat-v1/granola_goat-harvest-ibex-walker-mk2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-granola-goat-v1/granola_goat-harvest-ibex-walker-mk3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-granola-goat-v1/granola_goat-harvest-ibex-walker-mk4_idle_SW_00.png?v=1",
    },
    breakfast_burrito_boar: {
      1: "assets/sprites/runtime/war-machine-breakfast-burrito-boar-v2/breakfast_burrito_boar-brunch-cart-dozer-mk1_idle_SW_00.png?v=2",
      2: "assets/sprites/runtime/war-machine-breakfast-burrito-boar-v2/breakfast_burrito_boar-brunch-cart-dozer-mk2_idle_SW_00.png?v=2",
      3: "assets/sprites/runtime/war-machine-breakfast-burrito-boar-v2/breakfast_burrito_boar-brunch-cart-dozer-mk3_idle_SW_00.png?v=2",
      4: "assets/sprites/runtime/war-machine-breakfast-burrito-boar-v2/breakfast_burrito_boar-brunch-cart-dozer-mk4_idle_SW_00.png?v=2",
    },
    caesar_salamander: {
      1: "assets/sprites/runtime/war-machine-caesar-salamander-v2/caesar_salamander-sovereign-support-rig-mk1_idle_SW_00.png?v=2",
      2: "assets/sprites/runtime/war-machine-caesar-salamander-v2/caesar_salamander-sovereign-support-rig-mk2_idle_SW_00.png?v=2",
      3: "assets/sprites/runtime/war-machine-caesar-salamander-v2/caesar_salamander-sovereign-support-rig-mk3_idle_SW_00.png?v=2",
      4: "assets/sprites/runtime/war-machine-caesar-salamander-v2/caesar_salamander-sovereign-support-rig-mk4_idle_SW_00.png?v=2",
    },
    cucumber_cobra: {
      1: "assets/sprites/runtime/war-machine-cucumber-cobra-v2/cucumber_cobra-garden-coil-control-rig-mk1_idle_SW_00.png?v=2",
      2: "assets/sprites/runtime/war-machine-cucumber-cobra-v2/cucumber_cobra-garden-coil-control-rig-mk2_idle_SW_00.png?v=2",
      3: "assets/sprites/runtime/war-machine-cucumber-cobra-v2/cucumber_cobra-garden-coil-control-rig-mk3_idle_SW_00.png?v=2",
      4: "assets/sprites/runtime/war-machine-cucumber-cobra-v2/cucumber_cobra-garden-coil-control-rig-mk4_idle_SW_00.png?v=2",
    },
    avocado_axolotl: {
      1: "assets/sprites/runtime/war-machine-avocado-axolotl-v2/avocado_axolotl-pitguard-reactor-rig-mk1_idle_SW_00.png?v=2",
      2: "assets/sprites/runtime/war-machine-avocado-axolotl-v2/avocado_axolotl-pitguard-reactor-rig-mk2_idle_SW_00.png?v=2",
      3: "assets/sprites/runtime/war-machine-avocado-axolotl-v2/avocado_axolotl-pitguard-reactor-rig-mk3_idle_SW_00.png?v=2",
      4: "assets/sprites/runtime/war-machine-avocado-axolotl-v2/avocado_axolotl-pitguard-reactor-rig-mk4_idle_SW_00.png?v=2",
    },
    "banana_split_giraffe_boss": {
      1: "assets/sprites/runtime/war-machine-banana-split-giraffe-boss-v1/war-machine-banana-split-giraffe-boss_holograph-projector-giraffe-boss_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/war-machine-banana-split-giraffe-boss-v1/war-machine-banana-split-giraffe-boss_holograph-projector-giraffe-boss_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/war-machine-banana-split-giraffe-boss-v1/war-machine-banana-split-giraffe-boss_holograph-projector-giraffe-boss_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/war-machine-banana-split-giraffe-boss-v1/war-machine-banana-split-giraffe-boss_holograph-projector-giraffe-boss_idle_SW_00.png?v=1",
    },
    "cyber_brain_final_boss": {
      1: "assets/sprites/runtime/cyber-brain-final-boss-v1/cyber_brain_final_boss-overmind-core_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/cyber-brain-final-boss-v1/cyber_brain_final_boss-overmind-core_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/cyber-brain-final-boss-v1/cyber_brain_final_boss-overmind-core_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/cyber-brain-final-boss-v1/cyber_brain_final_boss-overmind-core_idle_SW_00.png?v=1",
    },
    "brainstem_wire_minion": {
      1: "assets/sprites/runtime/brainstem-wire-minions-v3-thin-outline/brainstem_wire_minion-1_idle_SW_00.png?v=1",
      2: "assets/sprites/runtime/brainstem-wire-minions-v3-thin-outline/brainstem_wire_minion-2_idle_SW_00.png?v=1",
      3: "assets/sprites/runtime/brainstem-wire-minions-v3-thin-outline/brainstem_wire_minion-3_idle_SW_00.png?v=1",
      4: "assets/sprites/runtime/brainstem-wire-minions-v3-thin-outline/brainstem_wire_minion-4_idle_SW_00.png?v=1",
      5: "assets/sprites/runtime/brainstem-wire-minions-v3-thin-outline/brainstem_wire_minion-5_idle_SW_00.png?v=1",
    },
  };
  const DEFEAT_STILL_SPRITES = {
    toast_tortoise: "assets/sprites/runtime/defeat-stills/toast-tortoise-defeat-food-v1.png",
    sushi_seal: "assets/sprites/runtime/defeat-stills/sushi-seal-defeat-food-v1.png",
    taco_tiger: "assets/sprites/runtime/defeat-stills/taco-tiger-defeat-food-v1.png",
    berry_bat: "assets/sprites/runtime/defeat-stills/berry-bat-defeat-food-v1.png",
    noodle_newt: "assets/sprites/runtime/defeat-stills/noodle-newt-defeat-food-v1.png",
    pancake_penguin: "assets/sprites/runtime/defeat-stills/pancake-penguin-defeat-food-v1.png",
    pretzel_python: "assets/sprites/runtime/defeat-stills/pretzel-python-defeat-food-v1.png",
    popcorn_porcupine: "assets/sprites/runtime/defeat-stills/popcorn-porcupine-defeat-food-v1.png",
    donut_dodo: "assets/sprites/runtime/defeat-stills/donut-dodo-defeat-food-v1.png",
    benedict_lobster: "assets/sprites/runtime/defeat-stills/benedict-lobster-defeat-food-v1.png",
    curry_crab: "assets/sprites/runtime/defeat-stills/curry-crab-defeat-food-v1.png",
    hot_chip_hamster: "assets/sprites/runtime/defeat-stills/hot-chip-hamster-defeat-food-v1.png",
    waffle_walrus: "assets/sprites/runtime/defeat-stills/waffle-walrus-defeat-food-v1.png",
    bagel_beaver: "assets/sprites/runtime/defeat-stills/bagel-beaver-defeat-food-v1.png",
    bao_bun_badger: "assets/sprites/runtime/defeat-stills/bao-bun-badger-defeat-food-v1.png",
    pepper_prawn: "assets/sprites/runtime/defeat-stills/pepper-prawn-defeat-food-v1.png",
    yogurt_yeti: "assets/sprites/runtime/defeat-stills/yogurt-yeti-defeat-food-v1.png",
    kimchi_chameleon: "assets/sprites/runtime/defeat-stills/kimchi-chameleon-defeat-food-v1.png",
    dumpling_armadillo: "assets/sprites/runtime/defeat-stills/dumpling-armadillo-defeat-food-v1.png",
    lemon_meringue_lynx: "assets/sprites/runtime/defeat-stills/lemon-meringue-lynx-defeat-food-v1.png",
    shakshuka_shark: "assets/sprites/runtime/defeat-stills/shakshuka-shark-defeat-food-v1.png",
    boba_basilisk: "assets/sprites/runtime/defeat-stills/boba-basilisk-defeat-food-v1.png",
    croissant_kraken: "assets/sprites/runtime/defeat-stills/croissant-kraken-defeat-food-v1.png",
    fortune_cookie_fox: "assets/sprites/runtime/defeat-stills/fortune-cookie-fox-defeat-food-v1.png",
    mochi_mammoth: "assets/sprites/runtime/defeat-stills/mochi-mammoth-defeat-food-v1.png",
    gingerbread_golem: "assets/sprites/runtime/defeat-stills/gingerbread-golem-defeat-food-v1.png",
    iceberg_oyster: "assets/sprites/runtime/defeat-stills/iceberg-oyster-defeat-food-v1.png",
    saltwater_taffy_otter: "assets/sprites/runtime/defeat-stills/saltwater-taffy-otter-defeat-food-v1.png",
    churro_cheetah: "assets/sprites/runtime/defeat-stills/churro-cheetah-defeat-food-v1.png",
    granola_goat: "assets/sprites/runtime/defeat-stills/granola-goat-defeat-food-v1.png",
    breakfast_burrito_boar: "assets/sprites/runtime/defeat-stills/breakfast-burrito-boar-defeat-food-v1.png",
    caesar_salamander: "assets/sprites/runtime/defeat-stills/caesar-salamander-defeat-food-v2.png",
    cucumber_cobra: "assets/sprites/runtime/defeat-stills/cucumber-cobra-defeat-food-v2.png",
    avocado_axolotl: "assets/sprites/runtime/defeat-stills/avocado-axolotl-defeat-food-v2.png",
    herb_hare: "assets/sprites/runtime/defeat-stills/herb-hare-defeat-food-v2.png",
    green_juice_goose: "assets/sprites/runtime/defeat-stills/green-juice-goose-defeat-food-v1.png",
    caprese_capybara: "assets/sprites/runtime/defeat-stills/caprese-capybara-defeat-food-v2.png",
    vinaigrette_viper: "assets/sprites/runtime/defeat-stills/vinaigrette-viper-defeat-food-v2.png",
    kelp_koala: "assets/sprites/runtime/defeat-stills/kelp-koala-defeat-food-v1.png",
    melon_mint_mantis: "assets/sprites/runtime/defeat-stills/melon-mint-mantis-defeat-food-v1.png",
    coconut_shrimp_sheep: "assets/sprites/runtime/defeat-stills/coconut-shrimp-sheep-defeat-food-v1.png",
    crab_cake_caterpillar: "assets/sprites/runtime/defeat-stills/crab-cake-caterpillar-defeat-food-v1.png",
    pico_de_gallo_gecko: "assets/sprites/runtime/defeat-stills/pico-de-gallo-gecko-defeat-food-v1.png",
    "banana_split_giraffe_boss": "assets/sprites/runtime/defeat-stills/banana-split-giraffe-boss-war-machine-defeat-v2.png?v=1",
  };
  const REALITY_DEFEAT_STILL_SPRITES = {
    toast_tortoise: "assets/sprites/runtime/defeat-stills/toast-tortoise-war-machine-defeat-v4.png?v=1",
    sushi_seal: "assets/sprites/runtime/defeat-stills/sushi-seal-war-machine-defeat-v2.png?v=1",
    taco_tiger: "assets/sprites/runtime/defeat-stills/taco-tiger-war-machine-defeat-v3.png?v=1",
    berry_bat: "assets/sprites/runtime/defeat-stills/berry-bat-war-machine-defeat-v1.png?v=1",
    noodle_newt: "assets/sprites/runtime/defeat-stills/noodle-newt-war-machine-defeat-v3.png?v=3",
    pancake_penguin: "assets/sprites/runtime/defeat-stills/pancake-penguin-war-machine-defeat-v1.png?v=1",
    pretzel_python: "assets/sprites/runtime/defeat-stills/pretzel-python-war-machine-defeat-v1.png?v=1",
    popcorn_porcupine: "assets/sprites/runtime/defeat-stills/popcorn-porcupine-war-machine-defeat-v2.png?v=2",
    yogurt_yeti: "assets/sprites/runtime/defeat-stills/yogurt-yeti-war-machine-defeat-v2.png?v=1",
    bagel_beaver: "assets/sprites/runtime/defeat-stills/bagel-beaver-war-machine-defeat-v2.png?v=1",
    bao_bun_badger: "assets/sprites/runtime/defeat-stills/bao-bun-badger-war-machine-defeat-v1.png?v=1",
    donut_dodo: "assets/sprites/runtime/defeat-stills/donut-dodo-war-machine-defeat-v2.png?v=1",
    kimchi_chameleon: "assets/sprites/runtime/defeat-stills/kimchi-chameleon-war-machine-defeat-v1.png?v=1",
    waffle_walrus: "assets/sprites/runtime/defeat-stills/waffle-walrus-war-machine-defeat-v3.png?v=3",
    dumpling_armadillo: "assets/sprites/runtime/defeat-stills/dumpling-armadillo-war-machine-defeat-v3.png?v=1",
    lemon_meringue_lynx: "assets/sprites/runtime/defeat-stills/lemon-meringue-lynx-war-machine-defeat-v3.png?v=1",
    shakshuka_shark: "assets/sprites/runtime/defeat-stills/shakshuka-shark-war-machine-defeat-v4.png?v=1",
    saltwater_taffy_otter: "assets/sprites/runtime/defeat-stills/saltwater-taffy-otter-war-machine-defeat-v3.png?v=1",
    croissant_kraken: "assets/sprites/runtime/defeat-stills/croissant-kraken-war-machine-defeat-v3.png?v=1",
    fortune_cookie_fox: "assets/sprites/runtime/defeat-stills/fortune-cookie-fox-war-machine-defeat-v3.png?v=1",
    mochi_mammoth: "assets/sprites/runtime/defeat-stills/mochi-mammoth-war-machine-defeat-v4.png?v=4",
    gingerbread_golem: "assets/sprites/runtime/defeat-stills/gingerbread-golem-war-machine-defeat-v3.png?v=1",
    boba_basilisk: "assets/sprites/runtime/defeat-stills/boba-basilisk-war-machine-defeat-v5.png?v=1",
    iceberg_oyster: "assets/sprites/runtime/defeat-stills/iceberg-oyster-war-machine-defeat-v4.png?v=1",
    herb_hare: "assets/sprites/runtime/defeat-stills/herb-hare-war-machine-defeat-v2.png?v=1",
    green_juice_goose: "assets/sprites/runtime/defeat-stills/green-juice-goose-war-machine-defeat-v2.png?v=2",
    caprese_capybara: "assets/sprites/runtime/defeat-stills/caprese-capybara-war-machine-defeat-v1.png?v=1",
    vinaigrette_viper: "assets/sprites/runtime/defeat-stills/vinaigrette-viper-war-machine-defeat-v1.png?v=1",
    kelp_koala: "assets/sprites/runtime/defeat-stills/kelp-koala-war-machine-defeat-v2.png?v=1",
    melon_mint_mantis: "assets/sprites/runtime/defeat-stills/melon-mint-mantis-war-machine-defeat-v1.png?v=1",
    coconut_shrimp_sheep: "assets/sprites/runtime/defeat-stills/coconut-shrimp-sheep-war-machine-defeat-v1.png?v=1",
    crab_cake_caterpillar: "assets/sprites/runtime/defeat-stills/crab-cake-caterpillar-war-machine-defeat-v1.png?v=1",
    pico_de_gallo_gecko: "assets/sprites/runtime/defeat-stills/pico-de-gallo-gecko-war-machine-defeat-v1.png?v=1",
    pepper_prawn: "assets/sprites/runtime/defeat-stills/pepper-prawn-war-machine-defeat-v1.png?v=1",
    hot_chip_hamster: "assets/sprites/runtime/defeat-stills/hot-chip-hamster-war-machine-defeat-v3.png?v=3",
    benedict_lobster: "assets/sprites/runtime/defeat-stills/benedict-lobster-war-machine-defeat-v2.png?v=1",
    curry_crab: "assets/sprites/runtime/defeat-stills/curry-crab-war-machine-defeat-v1.png?v=1",
    churro_cheetah: "assets/sprites/runtime/defeat-stills/churro-cheetah-war-machine-defeat-v2.png?v=3",
    "banana_split_giraffe_boss": "assets/sprites/runtime/defeat-stills/banana-split-giraffe-boss-war-machine-defeat-v2.png?v=1",
    granola_goat: "assets/sprites/runtime/defeat-stills/granola-goat-war-machine-defeat-v1.png?v=1",
    breakfast_burrito_boar: "assets/sprites/runtime/defeat-stills/breakfast-burrito-boar-war-machine-defeat-v2.png?v=2",
    caesar_salamander: "assets/sprites/runtime/defeat-stills/caesar-salamander-war-machine-defeat-v2.png?v=2",
    cucumber_cobra: "assets/sprites/runtime/defeat-stills/cucumber-cobra-war-machine-defeat-v2.png?v=2",
    avocado_axolotl: "assets/sprites/runtime/defeat-stills/avocado-axolotl-war-machine-defeat-v2.png?v=2",
    "cyber_brain_final_boss": "assets/sprites/runtime/defeat-stills/cyber-brain-final-boss-defeat-v1.png?v=1",
    "brainstem_wire_minion": {
      1: "assets/sprites/runtime/defeat-stills/brainstem-wire-minion-defeat-v3-thin-outline-tier1.png?v=1",
      2: "assets/sprites/runtime/defeat-stills/brainstem-wire-minion-defeat-v3-thin-outline-tier2.png?v=1",
      3: "assets/sprites/runtime/defeat-stills/brainstem-wire-minion-defeat-v3-thin-outline-tier3.png?v=1",
      4: "assets/sprites/runtime/defeat-stills/brainstem-wire-minion-defeat-v3-thin-outline-tier4.png?v=1",
      5: "assets/sprites/runtime/defeat-stills/brainstem-wire-minion-defeat-v3-thin-outline-tier5.png?v=1",
    },
  };

  window.FoodAnimalsUnitData = Object.freeze({
    CATALOG,
    DEFEAT_STILL_SPRITES,
    REALITY_DEFEAT_STILL_SPRITES,
    REALITY_RUNTIME_SPRITES,
    RUNTIME_SPRITES,
  });
})();
